### ISSUE TITLE
Public API for starting in the headers-state

### ISSUE THREAD

**Issue by judofyr** [nodejs/http-parser#108]
Multipart bodies are _almost_ like a HTTP req/res; they just don't have status line:

```
------------0xKhTmLbOuNdArY
Content-Disposition: form-data; name="text1"

hallo welt test123

------------0xKhTmLbOuNdArY
Content-Disposition: form-data; name="text2"


------------0xKhTmLbOuNdArY
Content-Disposition: form-data; name="upload"; filename="hello.pl"
Content-Type: application/octet-stream

#!/usr/bin/perl

use strict;
use warnings;

print "Hello World :)\n"

------------0xKhTmLbOuNdArY--
```

It would be nice if it was possible parse these headers (the body would just appear as a streaming/EOF-detected body) using http-parser.

**Comment by tdecaluwe** [comment]
Feeding it a status line is indeed a simple workaround, but a bit of a hacky solution. Would you accept a PR for this?

**Comment by indutny** [comment]
@tdecaluwe I don't think that it is a good idea. Through recent years, we have refactored http-parser pretty significantly internally, and exposing these states will lock us into a particular API just for this use-case.

Sorry, but won't fix.
