### ISSUE TITLE
Using url_callback and http_parser_parse_url()

### ISSUE THREAD

**Issue by vborza** [nodejs/http-parser#121]
Hi guys,
Firstly, I want to say, really good work. I have downloaded this library, because I am coding a packet parser for network communication, as part of plugin for MS Visio. Joyent/http parser looks great for my necessaries, but I have problem with parsing URL as char\* from my packets.
Can you give me, please, some usable example, how to use url_callback and http_parser_url() together please? I really need it for my bachelor thesis.
Thank you very much..

**Comment by Koceto1973** [comment]
Hi guys, I stumbled at the same problem -
on_url() callback brings me back the path pointer and size,
and http_parser_parse_url() does no work for me.
I tried to pass test url buffer as "http://192.168.1.6:3000/path?query=1" but that brought me back parsed fields completely mismatched. 

I checked this aproach: https://github.com/springmeyer/libuv-webserver/blob/master/webserver.cc
code line 215

Would really appreciate some guidance,
Best regards,
K.
