### ISSUE TITLE
proper behavior for wikipedia-style URIs?

### ISSUE THREAD

**Issue by bch** [nodejs/http-parser#130]
Hit  http://en.wikipedia.org/wiki/Main_Page, take a look at the resultant HTML and notice that lots of its refs are of a form: "//some.server/path/starts/here", but without any transport. Feeding that to parse_url current interprets the whole thing as a path. Should it better handle the initial "//"?

**Comment by Trott** [comment]
I have to imagine this is no longer an issue, as these types of URLs are seen in a lot of places. Can anyone on @nodejs/http-parser confirm and close this if appropriate?

**Comment by indutny** [comment]
@Trott I think it is the same. cc @bnoordhuis @mscdex

**Comment by bnoordhuis** [comment]
Yeah, that never changed and I don't think it's a good change either: `http_parser_parse_url()` doesn't have enough context to decide whether it's okay to interpret it as scheme-relative.

I'll close this out.  The workaround is to prefix the URL with the scheme before submitting it to `http_parser_parse_url()`, that avoids any ambiguity.
