### ISSUE TITLE
The 'test-strict' and 'test-nonstrict' projects do not build on Windows (VS2013 Update 2)

### ISSUE THREAD

**Issue by Meai1** [nodejs/http-parser#181]
There are about ~40 errors per project, but they are essentially all the same: Some macro syntax is apparently not supported in Visual Studio. For example here:

```
#define WITH_QUOTES 12
, {.name= "with quotes"
  ,.type= HTTP_REQUEST
  ,.raw= "GET /with_\"stupid\"_quotes?foo=\"bar\" HTTP/1.1\r\n\r\n"
  ,.should_keep_alive= TRUE
  ,.message_complete_on_eof= FALSE
  ,.http_major= 1
  ,.http_minor= 1
  ,.method= HTTP_GET
  ,.query_string= "foo=\"bar\""
  ,.fragment= ""
  ,.request_path= "/with_\"stupid\"_quotes"
  ,.request_url= "/with_\"stupid\"_quotes?foo=\"bar\""
  ,.num_headers= 0
  ,.headers= { }
  ,.body= ""
  }
```

It complains "syntax error: }" on the ,headers={} line and the '}' is squiggly red. This is an example error, there are a few others where it complains about syntax error ','.

Steps to reproduce:
have python on your path
svn co http://gyp.googlecode.com/svn/trunk build/gyp --revision 1831
"path to http-parser"> "path to gyp.bat" --depth 1
open solution in Visual Studio and click "build"

**Comment by jasnell** [comment]
@indutny... any reason to keep this open?
