### ISSUE TITLE
http_parser_parse_url crash when random string passed

### ISSUE THREAD

**Issue by mobiphil** [nodejs/http-parser#209]
was expecting to get only path UF_PATH retrieved when calling http_parser_parse_url without any schema or "//", instead the function crashes the host app.

it should either fail to fill any of the fields or just fill in path with full string if no schema "<schema>//.." specified

**Comment by indutny** [comment]
@mobiphil thanks for sharing this with us. May I kindly ask you to provide a test case for our convenience?

**Comment by mobiphil** [comment]
hi, happy to help, just try:

   struct http_parser_url u;
   char *url = "test";

   http_parser_parse_url(url, strlen(url), 0, &u) ;

**Comment by jay** [comment]
What is happening here is `http_parse_host` expects the `UF_HOST` field to be filled but it isn't. Refer to my PR for a fix.

In the case of `test` you'll see a parsing error and in the case of something like `example.com/test` you'll also see a parsing error. To parse those would mean to allow no schema. I know libcurl does this in its code but I'm not sure how it plays here. What the OP described will work though because a slash designates the path:
```
Parsing //, connect 0
Parse ok, result :
        field_set: 0x8, port: 0
        field_data[0]: unset
        field_data[1]: unset
        field_data[2]: unset
        field_data[3]: off: 0, len: 2, part: //
        field_data[4]: unset
        field_data[5]: unset
        field_data[6]: unset
```
Personally I want to be able to handle something like `example.com/test` so I will probably do something in my own fork to add a best-guess for schema if the url is missing it.

**Comment by mobiphil** [comment]
Thanks for your time for dealing with the issue. Among others I was intending to use the url parser for parsing of the GET command from a http header that, as you may know, does not contain the schema or server. So for a request like http://gliaeuoaeu.com it would issue a http header with "GET / HTTP/1.1." For http://gliaoeuo.com///// will issue a http header with "GET ///// HTTP/1.1" which I think is valid http. I think the url parser should interpret thus the slashes as virtual path elements rather than the double slash from the schema.

**Comment by craig65535** [comment]
@mobiphil Why not build a real URL using the value of the `Host` header before passing it into http_parser_parse_url?

**Comment by mobiphil** [comment]
Well, that was what I done, you can imagine. The bug was against the crash. The question is if doing what you advice is hackish or not. Without being perfectionist for sure it is not efficient to just concatenate strings because a library may not implement sthg. correctly. The question is what is the standard/advice described in protocol related documents.

**Comment by indutny** [comment]
Wait, hostname is not required. The crash is happening because the `http_parser_url` should be `memset` to all zeroes before the process. We require this for every other thing with various `_init()` functions, but forgot to document this.

Going to send a PR in a bit.

**Comment by indutny** [comment]
Should be fixed by https://github.com/joyent/http-parser/pull/225

**Comment by jasnell** [comment]
Closing. Can reopen if #225 didn't actually solve it
