### ISSUE TITLE
http_parser_execute not call..

### ISSUE THREAD

**Issue by tensafe** [nodejs/http-parser#239]
When get rst packets, I  try to use http_parser_execute (&parser_response, &response_settings_, NULL, 0) end the session, but did not call message_cb.

can i set 
parser.state = 61; /*s_body_identity_eof */

before call http_parser_execute ?

**Comment by jasnell** [comment]
@tensafe ... not sure if this is still an issue for you. The best bet is to ask in one of the user forums or IRC
