### ISSUE TITLE
Parser type HTTP_BOTH only works for first HTTP message encountered?

### ISSUE THREAD

**Issue by hissohathair** [nodejs/http-parser#250]
In my application I don't know for sure if I'm about to receive a HTTP request or response, so I've been using HTTP_BOTH as the type argument to http_parser_init. I then read in my data stream and call http_parser_execute as the data comes in. The first HTTP message is always OK, but if the next HTTP message is a different type (eg first is a request but second is a response) then the parser raises a HPE_INVALID_METHOD error.

You can reproduce this behaviour with the parsertrace.c command in contrib. For example if you feed it [two GET requests in a row](http://pastebin.com/M8Bs2s90) it traces both messages fine.  But if you feed it [one GET and one response in a row](http://pastebin.com/xzpXPrUA) it aborts with the same error.

Saving that second pastebin link to a file 'get-response.txt' and then calling parsertrace you'd get:

``` bash
$ ./contrib/parsertrace -b test-data/get-response.txt 

***MESSAGE BEGIN***

Url: http://www.google.com/
Header field: Host
Header value: www.google.com
Header field: Proxy-Connection
Header value: keep-alive
Header field: Cache-Control
Header value: max-age=0
Header field: Accept
Header value: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
Header field: User-Agent
Header value: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_8_2) AppleWebKit/537.17 (KHTML, like Gecko) Chrome/24.0.1312.52 Safari/537.17
Header field: X-Chrome-Variations
Header value: CK+1yQEIh7bJAQigtskBCKS2yQEIqLbJAQiptskBCLy2yQEI0IPKAQ==
Header field: DNT
Header value: 1
Header field: Accept-Encoding
Header value: gzip,deflate,sdch
Header field: Accept-Language
Header value: en-US,en;q=0.8
Header field: Accept-Charset
Header value: ISO-8859-1,utf-8;q=0.7,*;q=0.3

***HEADERS COMPLETE***


***MESSAGE COMPLETE***


***MESSAGE BEGIN***

Error: invalid HTTP method (HPE_INVALID_METHOD)
```

But maybe this is my error -- should I reset the http parser on message complete? I was doing that before but it seemed to cause issues with extra bytes (http_parser.c line 1901).

**Comment by indutny** [comment]
@hissohathair it is http-parser semantics to reset parser after each message, I'm +1 for documenting this if you have interest in this ;)

**Comment by hissohathair** [comment]
Absolutely. Thanks for confirming the need for reset.

I'm guessing I should
* Document the step in the README.md file
* Check the contrib examples and possibly change the examples there to show a parser reset after each message.

Then send pull request.

Anything else? Is this what you had in mind? Using http_parser a lot so happy to help out. :)

**Comment by indutny** [comment]
Sounds great :) Thank you for the help!

**Comment by a0viedo** [comment]
hey @hissohathair, I know it's been some time but this issue can be closed?

**Comment by hissohathair** [comment]
Yes, sorry @a0viedo this issue can be closed
