### ISSUE TITLE
MKCALENDAR method not supported

### ISSUE THREAD

**Issue by LordEidi** [nodejs/http-parser#255]
The http parser does not support the MKCALENDAR method as described in [1]. Which means it is not possible to implement a CalDAV server in node.js.

Others have the same problem as can be seen on mikedeboer/jsDAV#109. 

Some put a rewriting proxy in front of their app. Others (me included) added this ugly hack [3] to their program (rewriting the incoming data before it is handed over to the parser). Others just patched their copy of the http parser source and recompiled.

While the first and the last strategy are a pain in the neck, the second one linked on [2] does not work on the latest node.js version anymore (since the stream handling changed).

It would be nice if you could add the MKCALENDAR method to the list of accepted methods in the http parser so that us CalDAV app writers can continue to use node.js as our platform of choice.

[1] https://tools.ietf.org/html/rfc4791#section-5.3.1
[2] https://github.com/mikedeboer/jsDAV/issues/109
[3] https://github.com/LordEidi/fennel/blob/master/server.js -> starting at line 133.

**Comment by LordEidi** [comment]
Great, now that I submitted this issue, I stumbled over the changes from May 28th over here 1317eeca43b7c3c48a3f291483bb807648016d22 .

Sorry for bothering. Just leaves the question in what release that change will be published in. Am having Node v0.12.5 and do not see any changes.

**Comment by indutny** [comment]
@LordEidi I think iojs has it.

**Comment by LordEidi** [comment]
@indutny hmm does it make sense to move to iojs for that fix?

**Comment by indutny** [comment]
Depends on your needs :) It is very unlikely that v0.12 will get http-parser upgraded, because it is technically and introduction of a new feature.

**Comment by LordEidi** [comment]
Which leaves the question of when will v0.14 become a reality...

**Comment by indutny** [comment]
0.14 won't be released the next release will be most likely 4.x and will be a merged version of node.js and io.js

**Comment by jbergstroem** [comment]
Thinking this could be closed, now that nodejs 4.0+ is out and all.

**Comment by LordEidi** [comment]
Works with nodejs >= 4.
