### ISSUE TITLE
Example to Parse HTTP Response

### ISSUE THREAD

**Issue by nginxsantos** [nodejs/http-parser#263]
Can you please put an an example/usage to parse the HTTP Respnonse.
It will be much helpful.

**Comment by Shumen** [comment]
expecting as well

**Comment by ZuzooVn** [comment]
Did any one of you have the sample code?

**Comment by xiaokai-wang** [comment]
the test ?

**Comment by indutny** [comment]
I think benchmark could be more useful: https://github.com/nodejs/http-parser/blob/master/bench.c
