### ISSUE TITLE
About time for 2.6.0?

### ISSUE THREAD

**Issue by jasnell** [nodejs/http-parser#268]
@indutny @mscdex  ... it's been a few months since we've bumped http-parser in core. I'd like to propose that we go ahead and get it updated in master. I can take the lead on it.

**Comment by indutny** [comment]
Sounds good to me

**Comment by mscdex** [comment]
That's fine with me I guess.

**Comment by jbergstroem** [comment]
Landed in bee4817ebea0eaa592143c7825f5c96f040c84e4. Could someone create/push a tag?

**Comment by jasnell** [comment]
Tagged.
