### ISSUE TITLE
Not working for www.google.com

### ISSUE THREAD

**Issue by dthummel** [nodejs/http-parser#274]
Hi!

I have implemented a little test program with the lib. I have the problem that the code works for the index page of most tested major web sites. But not for www.google.com. The callback for on_message_complete is never called even if the whole page up to the </html> is feeded into the parser.

If I alternatively try to provide the complete page in a single data buffer with a trailing NUL and execute http_parser_execute with a buffer length of 0 I end up with 0 bytes parsed and no callback ever called.

Any suggestions?

Regards
Dietmar

**Comment by indutny** [comment]
@dthummel hello!

May I ask you to provide a sample code so I could help you? I'm quite sure that the parser is working fine with `www.google.com`, because node.js does work with it. It is most likely a matter of wrong configuration that causes a problems for you.

Cheers!

**Comment by dthummel** [comment]
Hi!

You are absolutely right. I wrote some sample code again and it works like a charm. Have to figure out what the difference and bug is on my side. Nevertheless I add the new test code maybe it helps someone else...

Thanks a lot and sorry for the false alarm!

    #include <sys/socket.h>
    #include <sys/types.h>
    #include <netinet/in.h>
    #include <arpa/inet.h>
    #include <unistd.h>
    #include <netdb.h>
    #include <string.h>
    #include <string>
    #include <map>
    #include <memory>
    #include <iostream>
    #include "http_parser.h"
    
    
    // helper class that represents the parser context
    struct parsercontext
    {
        std::map< std::string, std::string > mapHeaders;
        int iStatusCode;
        bool bHeaderParsed;
        bool bMessageParsed;
        std::string strBody;
    
        // only for temp usage
        std::string strLastHeaderField;
    };
    
    
    // function to stop with a message in case of an error
    void die( const std::string& strError )
    {
        std::cout << strError << std::endl;
        _exit( 1 );
    }
    
    
    // helper function to build up a simple http request
    std::string getRequest( const std::string& strHost )
    {
        // a result string
        std::string strResult( "GET / HTTP/1.1\r\n" );
        strResult += ( std::string( "Host: " ) + strHost + "\r\n" );
        strResult += "User-Agent: http/1.0\r\n";
        strResult += std::string( "Accept: *" ) + "/" + "*\r\n";
        strResult += "Connection: close\r\n";
        strResult += "\r\n";
    
        // leave with result
        return strResult;
    }
    
    // ---- various callback functions for the http_parser
    
    int onMessageBegin(http_parser* )
    {
        //std::cout << "onMessageBegin" << std::endl;
        return 0;
    }
    
    int onHeadersComplete(http_parser* parser)
    {
        //std::cout << "onHeadersComplete" << std::endl;
    
        // typecast data
        parsercontext* pContext = reinterpret_cast< parsercontext* >( parser->data );
    
        // set status code
        pContext->iStatusCode = parser->status_code;
    
        // remember that the header has been completely parsed
        pContext->bHeaderParsed = true;
    
        // success
        return 0;
    }
    
    int onMessageComplete(http_parser* parser)
    {
        //std::cout << "onMessageComplete" << std::endl;
    
        // typecast data
        parsercontext* pContext = reinterpret_cast< parsercontext* >( parser->data );
    
        // we are done
        pContext->bMessageParsed = true;
    
        // success
        return 0;
    }
    
    int onUrl(http_parser*, const char* c , size_t t)
    {
        //std::cout << "onUrl: " << std::string( c, t ) << std::endl;
        return 0;
    }
    
    int onHeaderField(http_parser* parser, const char* at, size_t length)
    {
    //    std::cout << "onHeaderField: " << std::string( at, length ) << std::endl;
    
        // typecast data
        parsercontext* pContext = reinterpret_cast< parsercontext* >( parser->data );
    
        // preserve this header field
        pContext->strLastHeaderField.assign( at, length );
    
        // success
        return 0;
    }
    
    int onHeaderValue(http_parser* parser, const char* at, size_t length)
    {
        //    std::cout << "onHeaderValue: " << std::string( at, length ) << std::endl;
    
        // typecast data
        parsercontext* pContext = reinterpret_cast< parsercontext* >( parser->data );
    
        // preserve this header field
        pContext->mapHeaders[ pContext->strLastHeaderField ] = std::string( at, length );
    
        // success
        return 0;
    }
    
    int onBody(http_parser* parser, const char* at, size_t length)
    {
        // typecast data
        parsercontext* pContext = reinterpret_cast< parsercontext* >( parser->data );
    
        // preserve this header field
        pContext->strBody += std::string( at, length );
    
        //std::cout << "onBody: ... " << pContext->strBody.substr( pContext->strBody.length() - 10 ) << std::endl;
    
        // success
        return 0;
    }
    
    int main(int argc, char *argv[])
    {
        // check for host name
        std::string strHost = ( argc > 1 ) ? argv[1] : "www.google.ch";
    
        // try to get the host name
        struct hostent* cHostEntity = gethostbyname( strHost.c_str() );
    
        // check for error
        if( NULL == cHostEntity ) die( "given host name not found" );
    
        // server address
        struct sockaddr_in cServAddr;
    
        // clean out
        memset( &cServAddr, 0, sizeof(cServAddr) );
    
        // set structure options
        cServAddr.sin_family = AF_INET;
        cServAddr.sin_port = htons( 80 );
        memcpy( &cServAddr.sin_addr, cHostEntity->h_addr, sizeof(cServAddr.sin_addr) );
    
        // create socket
        int iSocket = socket(AF_INET, SOCK_STREAM, 0 );
    
        // Check for error
        if ( iSocket < 0 ) die( "could not create socket" );
    
        // connect to peer
        int iResult = connect( iSocket, (struct sockaddr*) &cServAddr, sizeof(cServAddr) );
    
        // Check for error (ignores all the already acquired ressources in case of error)
        if ( iResult < 0 ) die( "could not connect peer" );
    
        // get request
        std::string strRequest( getRequest( strHost ) );
    
        // write some data
        iResult = write( iSocket, strRequest.c_str(), strRequest.length() );
    
        // check for error
        if ( iResult < 0 ) die( "could not write request" );
    
        // a parser settings struct
        struct http_parser_settings cSettings;
    
        // set up the callbacks
        cSettings.on_message_begin    = onMessageBegin;
        cSettings.on_headers_complete = onHeadersComplete;
        cSettings.on_message_complete = onMessageComplete;
        cSettings.on_url              = onUrl;
        cSettings.on_header_field     = onHeaderField;
        cSettings.on_header_value     = onHeaderValue;
        cSettings.on_body             = onBody;
    
        // the context
        parsercontext cContext;
    
        // a http parser instance
        http_parser parser;
    
        // set up the parser
        http_parser_init(&parser, HTTP_RESPONSE);
    
        // insert context
        parser.data = &cContext;
    
        // a receive buffer
        char chBuffer[ 16384 ];
    
        //me Receiving data
        while ( false == cContext.bMessageParsed )
        {
            // read data
            iResult = read( iSocket, &chBuffer, sizeof( chBuffer ) );
    
            // check for error
            if ( iResult < 0 ) die( "could not read from peer side" );
    
            // call the parser
            size_t iParsedBytes = http_parser_execute( &parser, &cSettings, chBuffer, iResult );
    
            // check for errors
            if (HTTP_PARSER_ERRNO(&parser) != HPE_OK) die( http_errno_name(HTTP_PARSER_ERRNO(&parser)) + std::string( http_errno_description(HTTP_PARSER_ERRNO(&parser)) ) );
        }
    
        // done
        close( iSocket );
    
        // output the body
        std::cout << cContext.strBody << std::endl;
    
        // success
        return 0;
    
        // this is sample code. ignore all the ressources that should be cleaned up
    }
