### ISSUE TITLE
Response without Header throws HPE_INVALID_CONSTANT

### ISSUE THREAD

**Issue by alangecker** [nodejs/http-parser#278]
theres the rumour that no HTTP-Headers are required, just an empty line/CRLF (e.g. @ http://www.tutorialspoint.com/http/http_responses.htm)
as far as i understood the official [RFC 2616](https://www.w3.org/Protocols/rfc2616/rfc2616-sec6.html) every response should have at least an status line

had to work with an HTTP-Server, which serves just HTML and drops, for performance reasons, everything not important. (all tested browser treat it as 200 OK)
i guess there are more server like that out there, which are not able to get connected by node's http module.

in my opinion node should be able to parse such responses.
what do you think?

--- 
**small test**
...if somebody wanna work on that, i'm no c-developer :D
```js
const net = require('net');
const http = require('http');

const exampleBody = '<html><body>Body</body></html>';

const server = net.createServer((client) => {
  client.write('\r\n');
  client.write(exampleBody);
  client.end();
});
server.listen(1234, () => {
  http.request('http://localhost:1234', (res) => {
    res.on('data', (chunk) => {
      console.log(chunk.toString()===exampleBody ? 'passed' : 'failed');
    })
    res.on('end', ()=>{server.close()})
  }).on('error',console.log)
});
```

**Comment by indutny** [comment]
I think that the protocol that this servers speaks is not HTTP, thus it should not be parsed by http-parser.

Clearly it is just sending the data with some CRLF prefix, there is nothing in specification that could allow this, and as you said status line MUST be present in response.

Sorry!

**Comment by alangecker** [comment]
yeah, you're right!
only the header makes it to an HTTP packet^^

**Comment by indutny** [comment]
It is not the headers, it is just a CRLF.
