### ISSUE TITLE
Possibility of a header-only library?

### ISSUE THREAD

**Issue by vinniefalco** [nodejs/http-parser#280]
What are the chances this could be made header-only?

**Comment by indutny** [comment]
I would say it is quite unlikely. May I ask you what is your use case, and why do you want it to be header-only?

**Comment by vinniefalco** [comment]
Its part of a larger library that is mostly header-only, I'm looking to convert the last bits of it that require translation units. Come to think of it, it might not be possible to make the parser header-only using only C, it would require C++. So I can see why that might be a non-starter. I appreciate the response.

**Comment by udp** [comment]
I would be strongly opposed to making the library header-only.  If you really, really need that, copy the c file into the h file and make the functions static?

FWIW I would never use a "header only" library.  Linkers exist for a reason.

**Comment by bnoordhuis** [comment]
```c
#include "http_parser.h"
#include "http_parser.c"
```
Any reason that wouldn't work for you?

**Comment by vinniefalco** [comment]
@bnoordhuis That would violate the one definition rule if http_parser.c were included in two or more TUs.

@udp I guess you've never used boost or C++ standard library containers - they are mostly header-only.

**Comment by bnoordhuis** [comment]
> That would violate the one definition rule if http_parser.c were included in two or more TUs.

Wrap the includes in an anonymous namespace?

**Comment by udp** [comment]
@vinniefalco That's because they're mostly templated classes, so they have to be.  Putting implementations in headers unnecessarily is going to break incremental building, introduce code duplication, ...

**Comment by vinniefalco** [comment]
I don't think its going to be practical so I'll close this
