### ISSUE TITLE
HPE_INVALID_HEADER_TOKEN error on wordpress.org due to X-Olaf header since two days

### ISSUE THREAD

**Issue by stefan-hausmann** [nodejs/http-parser#284]
when using request module to fetch content from `http://wordpress.org/,` I get error
` { [Error: Parse Error] bytesParsed: 228, code: 'HPE_INVALID_HEADER_TOKEN' }`
since two days without having changed my node.js version (v.4.3.0 on ubuntu linux) nor having updated any node module.

returned http response headers (currently) are
`HTTP/1.1 200 OK
  Server: nginx
  Date: Thu, 18 Feb 2016 08:49:25 GMT
  Content-Type: text/html; charset=utf-8
  Transfer-Encoding: chunked
  Connection: keep-alive
  Vary: Accept-Encoding
  Strict-Transport-Security: max-age=360
  X-Olaf: \342\233\204
  X-Frame-Options: SAMEORIGIN
  X-nc: EXPIRED lax 249`

seems that the unnecessary and childish ` X-Olaf: \342\233\204` header's value cannot be parsed correctly due to some kind of encoding problems.

I do not have these problems on node.js v4.2.3 on windows.

I'm not sure if this is even the right issue tracker here for this problem, but maybe.
Can it be that this is somewhat related to #282 ?

**Comment by stefan-hausmann** [comment]
error doesn't occur now anymore, without me having updated any component.

**Comment by regevbr** [comment]
https://github.com/creationix/http-parser-js fixed the issue for me

**Comment by regevbr** [comment]
https://github.com/creationix/http-parser-js fixed the issue for me
