### ISSUE TITLE
.NET wrapper?

### ISSUE THREAD

**Issue by marler8997** [nodejs/http-parser#288]
The company I work for has need for a .NET http parser.  We have developed our own but it is no where near the quality of this one.  I've been thinking about either porting this parser to .NET or writing a .NET wrapper around the interface.  I would prefer writing a wrapper so both versions would be easier to maintain

I wanted to see what other thought of this idea?  If a wrapper was created, should it go in it's own repo?  Is anyone open to the idea of keeping a .NET wrapper in this repo?  I'll be thinking about the best path moving forward but I'd love input from others.

Note: If I did create a .NET wrapper, I would attempt to match the current C interface as close as possible.  To the point that the .NET http header data would be represented as byte arrays to prevent unnecessary marshalling between .NET's UTF-16 strings and HTTP's ascii encoding.  It may or may not require "unsafe" .NET code...won't be sure until I start implementing it.

**Comment by indutny** [comment]
I like the idea, and I think wrapper should go its own repo. Sounds like a lovely idea!
