### ISSUE TITLE
Unnecessary errors when Content-Length header is present with Transfer-Encoding: chunked

### ISSUE THREAD

**Issue by cbargren** [nodejs/http-parser#289]
https://github.com/nodejs/http-parser/blob/master/http_parser.c#L1787 The parser errors out when the Content-Length encoding is present with the Transfer-Encoding set as chunked. While this _is_ invalid, the [W3 specification](https://www.w3.org/Protocols/rfc2616/rfc2616-sec4.html#sec4.4) for HTTP messages says that:

> If the message does include a non- identity transfer-coding, the Content-Length MUST be ignored

Ignored, rather than rejected. Perhaps, it should simply clear out the Content-Length and continue on as normal rather than erroring out.

**Comment by johnhaley81** [comment]
To add a little more to this issue, this is breaking any HTTP(S) communication to BitBucket since that's how they form their response to the request.

**Comment by johnhaley81** [comment]
@indutny would you accept a PR that fixes this issue?

**Comment by indutny** [comment]
RFC 2616 is obsoleted by RFC 7230. Here is [the quote][0] from the latter one:

```
If a message is received with both a Transfer-Encoding and a
       Content-Length header field, the Transfer-Encoding overrides the
       Content-Length.  Such a message might indicate an attempt to
       perform request smuggling (Section 9.5) or response splitting
       (Section 9.4) and ought to be handled as an error.
```

[0]: https://tools.ietf.org/html/rfc7230#section-3.3.3

**Comment by cbargren** [comment]
Hm... Right you are. Looks like Bitbucket needs to get it together. :) thanks for your response!

**Comment by alvin** [comment]
https://bitbucket.org/site/master/issues/12673/remove-the-content-length-header-http
