### ISSUE TITLE
White spaces in header fields will cause parser failed

### ISSUE THREAD

**Issue by chenzhiwei** [nodejs/http-parser#297]
When the header fields contains white spaces, it will failed.

A sample case, there is a white space before colon in header field.

```
Content-Length : 5\r\n
```

**Comment by indutny** [comment]
I believe http-parser will fail only in a strict mode. May I ask you to share more details with us?

**Comment by chenzhiwei** [comment]
When the http response header is something like this:

```
HTTP/1.1 200 OK\r\n
Content-Length : 123\r\n
\r\n
body data
```

Please pay attention to the white spaces after `Content-Length` and before the colon.

I encountered this error in Mesos project: https://github.com/apache/mesos/commit/b2c92eef8107a8ac575ae665d1dfe5e8fb906e28#diff-cce67628b066393859924dbdfc3e0fb5L658

**Comment by indutny** [comment]
I indeed see the whitespace before the colon, but still not sure what kind of failure you are experiencing. From what I have tried a week ago, it really looked like http-parser supports whitespace before the colon.

May I ask you help me understand it?

**Comment by chenzhiwei** [comment]
Yes, I thought http-parser 2.6.2 solved this issue, but actually not.

You can insert a white space in this line, then do a make action, it will show you errors.

https://github.com/nodejs/http-parser/blob/v2.6.2/test.c#L1172

**Comment by chenzhiwei** [comment]
More detailed:

There is a call `size_t parsed = http_parser_execute(&parser, &settings, data, length);`, if the data is:

```
HTTP/1.1 200 OK\r\n
Content-Length : 123\r\n
\r\n
body data
```

The `parsed` and the real `length` are not same.

**Comment by chenzhiwei** [comment]
@indutny Could you take a look about this issue? Thanks.

**Comment by chenzhiwei** [comment]
Set the `HTTP_PARSER_STRICT=0` solved my issue, thanks.
