### ISSUE TITLE
Content-Length 

### ISSUE THREAD

**Issue by SpenZerX** [nodejs/http-parser#298]
Hello,

i am wondering, parser extracts Content-Length correct (at POST Method) and stores it.

In Header Complete callback Content-Length is still correct. 

In Body-Data-Callback (which should store body data?) Content-Length is 0, (cleared).

WHY?

Or is it required to indicate EOF by calling http_parser_execute  with len=0?

**Comment by indutny** [comment]
@SpenZerX this field is used for internal bookkeeping. We decrement it when parsing new data to determine where the next http request/response will start.

Thanks for asking!
