### ISSUE TITLE
Dose http_parser_execute *data param must be a complete HTTP package ?

### ISSUE THREAD

**Issue by ldcsaa** [nodejs/http-parser#302]
size_t http_parser_execute(http_parser *parser,
                           const http_parser_settings *settings,
                           const char *data,
                           size_t len);

my question is : on the TCP layer, it's stream protocol, usually RECV operation can not receive complete http package. if *data param must be a complete http package, then the tcp server need to do something like pre-processing to distinguish a complete http package. It would be increase the complexity of the TCP server.

how we should deal with it? Thanks very much !

**Comment by indutny** [comment]
Hello!

If feeded partial data, parser will emit partial data via callbacks. The whole project is built on the concept of working with partial data, so you should be safe to go!

Cheers,
Fedor.
