### ISSUE TITLE
Request line can miss HTTP/x.x

### ISSUE THREAD

**Issue by geek** [nodejs/http-parser#304]
I did notice that the following is considered valid, where the `HTTP-Version` part of the request line is missing.  

https://www.w3.org/Protocols/rfc2616/rfc2616-sec5.html#sec5.3

```
GET ssh:///\r\n\r\n
```

I have code to demonstrate the issue using node, but it seems like an http-parser issue, which is why I am logging here: 

```js
const Http = require('http');
const Url = require('url');

const server = Http.createServer((req, res) => {
    res.writeHead(200);
    res.end('Hello World');
});

server.listen(8080);
```

```js
const Net = require('net');

const client = Net.connect(8080, () => {
    client.write('GET ssh:///\r\n\r\n');
    client.pipe(process.stdout);
});
```

The request works and you get a valid response.

**Comment by vinniefalco** [comment]
I believe this is valid HTTP 0.9, which `http-parser` appears to support:
https://www.w3.org/Protocols/HTTP/AsImplemented.html

**Comment by indutny** [comment]
Yep, AFAIK it is like @vinniefalco said. Thank you!

**Comment by geek** [comment]
We should drop support for parsing pre HTTP 1.0.
