### ISSUE TITLE
Parsing requests\responses data from async sockets

### ISSUE THREAD

**Issue by rayrapetyan** [nodejs/http-parser#306]
What are the guidelines for parsing req\res from async sockets? There must be a way to distinguish errors and "wait more" states from the parser, but I don't see how to do that. Please suggest.

**Comment by indutny** [comment]
The error case is very easy to distinguish: https://github.com/nodejs/http-parser/blob/master/http_parser.h#L320-L321 Quote:

```C
/* Executes the parser. Returns number of parsed bytes. Sets
 * `parser->http_errno` on error. */
```

There is no "wait more" state in a parser, because it does not accumulate data internally, and just spits out chunks of incoming data in callbacks.

**Comment by rayrapetyan** [comment]
This makes no sense for me.
E.g. if you received "GET /joyent/" from a socket, parser will return 0 - "success" and will call "on_url" cb. Caller will see a "valid" URL in cb. 
However, the HTTP message is not complete, there are more URL chars coming from socket (e.g. it could be /joynet/a=1&b=2... etc).

So how caller should know if it need to wait for more characters or proceed with a part of the URL received?

**Comment by indutny** [comment]
Caller should accumulate data until on_headers_complete is called.

**Comment by rayrapetyan** [comment]
Is there a right way to determine the HTTP message is complete after calling http_parser_execute? http_body_is_final works only for messages actually having some body... The only way to determine if message is complete is from on_message_complete cb, but this seems like an unnecessary limitation. Maybe there is some undocumented flag to check if message is complete without using callbacks at all?

**Comment by indutny** [comment]
@rayrapetyan what if you fed two concatenated messages to `http_parser_execute`? Clearly, a callback is the only way to get this information in a relevant (request) context.

**Comment by rayrapetyan** [comment]
Yes, it can be handy in some scenarios (when http_parser is used as an independent "service" for multiple different connections), but what about more simple scenario, where we use one http_parser per connection, and all we need to do after recv - make sure that incoming HTTP message is now complete and valid (all within the same context\function and that we should not call recv anymore and just start to process a received message)? Of course we can define on_message_complete, then call "pause_http_parser" from this callback and use passed "data" pointer to restore a context, but it's against "lex parsimoniae"...

I've noticed http_parser sets state to "s_start_req\s_start_res" right before calling on_message_complete. Can we safely use this flag as an indication that message was properly and completely processed after calling http_parser_execute?

And btw just curious - why does http_parser provides "http_body_is_final" method, but not a similar "http_message_is_processed" or something like that?

**Comment by indutny** [comment]
connection != request, one connection usually carries several requests using keep-alive (which is default for HTTP/1.1).

**Comment by rayrapetyan** [comment]
Nevermind, I've just realized http_parser doesn't keep any parts of a parsed message anywhere and have no any use without callbacks and handlers in which caller should take care of all message parts lol ). Sorry man!
