### ISSUE TITLE
Support for static library build

### ISSUE THREAD

**Issue by oldmancoyote** [nodejs/http-parser#310]
I see there is support for a shared .so library but would you mind if I added support for a static .a library?

**Comment by indutny** [comment]
@oldmancoyote I think `make http_parser.o` will do this, won't it?

**Comment by oldmancoyote** [comment]
A .o is an object file while a .a is a static library file. There is no support in the Makefile to output a static library.

**Comment by indutny** [comment]
Sounds good to me then! Thank you for proposal.

(Though, .a and .o both can be used to link something statically)

**Comment by craig65535** [comment]
I think the Makefile already produces a `.a` file. See https://github.com/nodejs/http-parser/blob/master/Makefile#L108

```
$ make package
cc  -I. -DHTTP_PARSER_STRICT=0  -Wall -Wextra -Werror -O3  -c http_parser.c
ar rcs libhttp_parser.a http_parser.o
$ ls *.a
libhttp_parser.a
```

**Comment by ploxiln** [comment]
you could try cherry-picking this commit from my fork, which includes a few "fixups" for the Makefile, among which making "install" also install the static library
https://github.com/ploxiln/http-parser/commit/77dea2aacc0ab02d7ddb3dd98b0a258b01c324e1

**Comment by indutny** [comment]
@craig65535 I think your comment is correct.

@ploxiln I know I haven't been super fast on PRs, but would you care to open one if you think it is a good addition.

**Comment by junjiemars** [comment]
@craig65535 ```make package``` should do, it's better if add a ```install-package``` make target.
