### ISSUE TITLE
uri-parser disallows valid characters in scheme?

### ISSUE THREAD

**Issue by vinniefalco** [nodejs/http-parser#312]
From rfc3986:
```
scheme        = ALPHA *( ALPHA / DIGIT / "+" / "-" / "." )
```

However, `parse_url_char` uses this BNF:
```
scheme        = 1#ALPHA
```

See:
https://github.com/nodejs/http-parser/blob/master/http_parser.c#L515

Is this by design?

**Comment by ploxiln** [comment]
dup of #275 (and addressed in #276)

**Comment by vinniefalco** [comment]
Hmm... its fixed at the tip of master?

**Comment by ploxiln** [comment]
nope

**Comment by vinniefalco** [comment]
Oh, I see, #276 simply hasn't been merged. I'll close this.
