### ISSUE TITLE
http-parser loose interpretation of HTTP-version

### ISSUE THREAD

**Issue by vinniefalco** [nodejs/http-parser#316]
rfc7230 defines

```
   HTTP-version = HTTP-name "/" DIGIT "." DIGIT
```

In other words, one and exactly one digit must appear both to the left and to the right of the period. However, http-parser allows multiple digits including leading zeroes:
https://github.com/nodejs/http-parser/blob/f2c26ee500ab3921010fa7ec66243365611e77dd/http_parser.c#L825

Suggested fix, if `HTTP_PARSER_STRICT` is defined then transition to an intermediate state requiring a dot after the first digit, etc...

**Comment by aldanor** [comment]
Should be closed by #366
