### ISSUE TITLE
There's a brand new C++, header-only HTTP parser here!

### ISSUE THREAD

**Issue by vinniefalco** [nodejs/http-parser#322]
I bit the bullet and re-implemented this http-parser in C++ for my library Beast. Its now header-only, and strict. Its pretty competitive in terms of performance and ease of use. And it has quite extensive test coverage:
https://github.com/vinniefalco/Beast/blob/master/include/beast/http/basic_parser_v1.hpp#L87

and documentation:
http://vinniefalco.github.io/beast/beast/ref/http__basic_parser_v1.html

100% test coverage:
https://codecov.io/gh/vinniefalco/Beast/src/4a4bf95bfefd8f7f5cde654cd394d14aabe4f6e9/include/beast/http/impl/basic_parser_v1.ipp

Beast is here:
https://github.com/vinniefalco/Beast

Beast provides C++ implementations of HTTP and WebSocket using Boost. Beast is entirely header-only.

**Comment by Fishrock123** [comment]
cc probably @jasnell

**Comment by indutny** [comment]
Thank you so much for sharing this with us! I'm not sure how to act on this issue, however. Is this a question, bug report, or improvement suggestion? Could it be closed?

**Comment by vinniefalco** [comment]
@indutny I'm not sure that any action is required, just saying that if there are users who need a HTTP parser that is header-only, there is now a solution. And also this is my way of saying thanks to the people who developed nodejs/http-parser, without which my implementation would not be possible.

**Comment by indutny** [comment]
Aaaah, you're more then welcome! I'm sorry, but this issue will be closed, though :)

👍

**Comment by mkozjak** [comment]
...or you can use our [recurse](https://github.com/qaap/recurse) micro web-framework's tool to merge header and implementation files into a header. :)

https://github.com/qaap/recurse/blob/master/tools/http_parser_merge.py
