### ISSUE TITLE
Content-Length Header

### ISSUE THREAD

**Issue by saschaarthur** [nodejs/http-parser#324]
Hello,

I just run into in issue with your http_parser.c.

I digged a bit into your Code, noticing that youre using something similiar to a state-machine to match a substring of the server returning Headers. (https://github.com/nodejs/http-parser/blob/master/http_parser.c#L1301)

This approach is fast and works in theorie if youre parsing the rfc7230. But well yeah, the outside world - also in my case not always stick fully to this RFC.

Were using a custom REST implementation and adding additional Headers.

We added for example for furher information "Content-Length-Uncompressed", because we gzipping our content, but need also the real size.

A Change in this commit (https://github.com/nodejs/http-parser/commit/e2e467b91262246b339fb3d80c8408d498b4a43b) (https://github.com/nodejs/http-parser/blame/master/http_parser.c#L1369) broke nodejs for working with our rest in the latest version. 

We now changed this Header Name on our side, but you can and should consider to parse the full header String instead only of a Substring which is a bit dangerous and brings unwanted side-effects.

**Comment by Fishrock123** [comment]
cc @nodejs/http

**Comment by bnoordhuis** [comment]
https://github.com/nodejs/http-parser/pull/325

**Comment by jasnell** [comment]
Yes, this is an unfortunate side effect of the current parsing model. I see @bnoordhuis already has a pr for this specific issue but there are more systemic problems with the current parser that I'll be looking at more in depth starting in the coming weeks.
