### ISSUE TITLE
on_message_complete callback doesn't invoke after an answer from squid proxy server

### ISSUE THREAD

**Issue by ykochenkov** [nodejs/http-parser#327]
Hello.
After the CONNECT request the squid proxy server response
"HTTP/1.1 200 Connection established\r\n\r\n".

After parsing this string the "on_message_complete" callback doesn't invoke. 
I use code below:

http_parser _parser = {0};
http_parser_settings _parserSettings = {0};
_parserSettings.on_message_complete = onMessageComplete; // callback
.........
http_parser_init(&_parser, HTTP_BOTH);
size_t offset = http_parser_execute(&_parser, &_parserSettings,.........

**Comment by rayrapetyan** [comment]
That's because "Content-Lenght" is not part of the response. In this case, you should perform one more recv call on the socket, obtain zero bytes and call: 
`http_parser_execute(&parser, &settings, your_empty_buf, 0); `
and http_parser will call on_message_complete this time.

**Comment by binarytrails** [comment]
I just wanted to say, thank you for this. It made my day.

**Comment by 0wnrepo** [comment]
> That's because "Content-Lenght" is not part of the response. In this case, you should perform one more recv call on the socket (you should do it anyway, because there is no any evidence that squid is not going to send some message body), obtain zero bytes and call:
> `http_parser_execute(&parser, &settings, your_empty_buf, 0); `
> and http_parser will call on_message_complete this time.

But how can one know that another rcv call on the socket is required?
