### ISSUE TITLE
Use `git-secure-tag` for releases

### ISSUE THREAD

**Issue by indutny** [nodejs/http-parser#328]
This provides stronger security guarantees for signed tags, will also make things more secure for `gypkg` 😉 

See: https://github.com/nodejs/node/pull/7603
See: https://github.com/indutny/git-secure-tag

cc @mscdex @jasnell

**Comment by jasnell** [comment]
+1 SGTM

**Comment by indutny** [comment]
Here goes first release https://github.com/nodejs/http-parser/releases/tag/v2.7.1 with git-secure-tag.

Thanks!
