### ISSUE TITLE
Overflow detection on chunk trailers

### ISSUE THREAD

**Issue by scunningham** [nodejs/http-parser#33]
In reading over the code, I noticed that chunk trailers were excluded in the test PARSING_HEADER.  This has the effect of allowing chunk header parsing to continue indefinitely if an attacker crafts a trailer such as:

<pre>
...
"\r\n0\r\n"  // end of chunk
"overflow: " // header start
"xxxxxxxxxx......" 1 gigabyte of data
</pre>

The on_header_value callback will get called as each buffer that is fed to the parser is completed, but the callback consumer is probably not expecting the header value to grow unbounded.

Is there any reason the parser cannot or should not check for header size overflow when parsing chunk trailers?  Testing I've done indicates that just removing the check does the trick (see <a href=https://github.com/scunningham/http-parser/commit/5f7bf0da695fdc23772d17d62353cc3249115520>trailer_overflow_patch</a>)

**Comment by quinnj** [comment]
I know this issue is pretty old, but I wondered what the fix was, and more generally, how are chunk trailers handled? They seem to not be included in the request headers. Are they just ignored?

**Comment by indutny** [comment]
https://github.com/nodejs/http-parser/commit/5f7bf0da695fdc23772d17d62353cc3249115520 ?
