### ISSUE TITLE
Windows x64 compile warning

### ISSUE THREAD

**Issue by ldcsaa** [nodejs/http-parser#333]
1>......\Common\Src\http\http_parser.c(1330): warning C4244: '+=' : conversion from '__int64' to 'uint32_t', possible loss of data
1>......\Common\Src\http\http_parser.c(1441): warning C4244: '+=' : conversion from '__int64' to 'uint32_t', possible loss of data
1>......\Common\Src\http\http_parser.c(1610): warning C4244: '+=' : conversion from '__int64' to 'uint32_t', possible loss of data
1>......\Common\Src\http\http_parser.c(2198): warning C4244: '=' : conversion from '__int64' to 'uint16_t', possible loss of data
1>......\Common\Src\http\http_parser.c(2205): warning C4244: '=' : conversion from '__int64' to 'uint16_t', possible loss of data
1>......\Common\Src\http\http_parser.c(2217): warning C4244: '=' : conversion from '__int64' to 'uint16_t', possible loss of data
1>......\Common\Src\http\http_parser.c(2226): warning C4244: '=' : conversion from '__int64' to 'uint16_t', possible loss of data
1>......\Common\Src\http\http_parser.c(2326): warning C4244: '=' : conversion from '__int64' to 'uint16_t', possible loss of data

would you please fix it ?

**Comment by indutny** [comment]
Sorry for a belated reply. What version are you using when getting these errors? Line numbers doesn't seem to match the current master.
