### ISSUE TITLE
Pipelined requests and error handling

### ISSUE THREAD

**Issue by npmccallum** [nodejs/http-parser#338]
If you attempt to call `http_parser_execute()` with a buffer containing `GET / HTTP/1.1\r\n\r\nG` you receive the HPE_INVALID_METHOD. What I had expected was that no error would be thrown an that I would instead get a short number of bytes read. This would allow me to remove the first request from the buffer and then present the `G` back to `http_parser_execute()` on the next bit of data received.

Am I perhaps using the API wrong?

**Comment by 2underscores-vic** [comment]
AFAIK HTTP 1.1 request has to contain at least "Host" header

**Comment by npmccallum** [comment]
While that is true, it is irrelevant to this bug. The results are the same with a Host header.

**Comment by bnoordhuis** [comment]
> What I had expected was that no error would be thrown an that I would instead get a short number of bytes read.

It does, doesn't it?  http_parser_execute() returns the number of consumed bytes and sets `.http_errno` as a side effect.  If it's not working for you, please post your code.

**Comment by npmccallum** [comment]
https://github.com/latchset/tang/blob/master/src/tangd.c#L244

My expectation was that http_parser_execute() would attempt to parse, at most, one request in a single call. Instead, it attempts to parse all requests in the buffer.

I fully admit that I might be using it wrongly. However, the expectations here aren't exactly documented.

How should I attempt to distinguish between "the buffer contains a malformed request" and "the buffer contains one or more complete requests and a partial request"?

**Comment by indutny** [comment]
@npmccallum the API provides callbacks for request start/end, if one has a dangling start of request without the end - the request wasn't fully parsed.

**Comment by npmccallum** [comment]
@indutny Yes. I understand. That's not my question.

**Comment by npmccallum** [comment]
My question is how to distinguish between "the data in the buffer can never be a valid HTTP request" and "more data is needed."

**Comment by ploxiln** [comment]
cannot reproduce with 2.7.1

```c
#include <stdio.h>
#include <string.h>
#include "http_parser.h"

int on_message_begin(http_parser *parser)
{
	printf("on_message_begin\n");
	return 0;
}
int on_message_complete(http_parser *parser)
{
	printf("on_message_complete\n");
	return 0;
}

int main()
{
	const char *input = "GET / HTTP/1.1\r\n\r\nG";

	http_parser parser;
	http_parser_settings settings = {
		.on_message_begin = on_message_begin,
		.on_message_complete = on_message_complete,
	};
	http_parser_init(&parser, HTTP_REQUEST);

	size_t ret = http_parser_execute(&parser, &settings, input, strlen(input));
	enum http_errno err = HTTP_PARSER_ERRNO(&parser);
	printf("strlen=%zu ret=%zu errno=%d errstr=%s\n",
	       strlen(input), ret, err, http_errno_name(err));
	return 0;
}
```

```
$ gcc -Wall -o testpart testpart.c http_parser.c
$ ./testpart
on_message_begin
on_message_complete
on_message_begin
strlen=19 ret=19 errno=0 errstr=HPE_OK
```

**Comment by npmccallum** [comment]
@ploxiln Thanks! I'm getting the same result with this code, so I'm obviously doing something wrong. I'll investigate. I can reopen this if I find a further bug.
