### ISSUE TITLE
Unexpected behaviour with invalid first line of request

### ISSUE THREAD

**Issue by ubergesundheit** [nodejs/http-parser#340]
Consider the HTTP request `GET /path?param=This is invalid HTTP/1.1` which is missing escaping of whitespace.

Now run the http server hello world example of node (6.7.0) and send the request to the server either with telnet or curl.

I would expect the server to respond with a `400 Bad Request`, but the code just waits and does nothing.

Is this behaviour intentional? HTTP servers in other languages (at least golang and python) respond with `400 Bad Request`

**Comment by indutny** [comment]
I can't really reproduce it. Would you care to provide a test case?

**Comment by indutny** [comment]
To make it clearer, it doesn't send 400 indeed, but this behavior is configurable. Default one is to close connection.

**Comment by ubergesundheit** [comment]
I should have included a test case in the first case. I cannot reproduce it either at this time..
The next time I encounter this behaviour I'll make a test case !
