### ISSUE TITLE
always report Parse Error HPE_INVALID_CONSTANT on zadego.com

### ISSUE THREAD

**Issue by octarrow** [nodejs/http-parser#341]
safari, chrome, curl can access the website without any issue but nodejs can't

here's the code to reproduce the issue. 

var request = require('request');
request('http://www.zadego.com', function (error, response, body) {
    if(error) console.log(error);
});

An easy way to test is to copy and run the above code on https://runkit.com/npm/request

**Comment by indutny** [comment]
The problem with that page is that it sends more data that is advertised in `Content-Length`. This is clearly invalid behavior, and I don't see a reason why such violation may be tolerated by http-parser. Sorry!
