### ISSUE TITLE
Semver compatibility for API/ABI?

### ISSUE THREAD

**Issue by Qantas94Heavy** [nodejs/http-parser#343]
Given that there have been breaking changes within 2.x in the past, is there any policy about whether the API/ABI would be stable for a given version or not (similar to say libuv)?

**Comment by indutny** [comment]
@Qantas94Heavy which particular changes did break ABI compatibility?

**Comment by Qantas94Heavy** [comment]
I think this was a while back with the older versions (like 2.4 or 2.5 or something), but I just meant it as a general question.

**Comment by indutny** [comment]
General policy disallows us to break ABI unless this is a major version bump. Hope this helps!
