### ISSUE TITLE
Swift Port - request for OSS License modification

### ISSUE THREAD

**Issue by dsperling** [nodejs/http-parser#344]
Smith Micro has started a Swift port of http-parser on a fork here:
https://github.com/smithmicro/HTTPParser

While the project is not ready to be included in projects like Kitura, the Swift team has contacted us requested that the project be included in the **Swift Benchmark Suite**.  In order for that to happen, the code would need to be under the Apache2 license.

The request from the authors is to see if we could get a **dual license exception** such that HTTPParser could be included in future Swift benchmarks.  Is this possible?

There is a discussion going on in Kitura project with some additional background.
https://github.com/IBM-Swift/Kitura-net/pull/55

Thanks for your consideration.

**Comment by gottesmm** [comment]
@dsperling Thanks!

**Comment by indutny** [comment]
cc @mikeal 

I'm not sure if there are any legal complications to this, but thanks for bringing it up!

**Comment by mikeal** [comment]
We'd have to send it to the board to get a legal review. What is the issue with the current license? It's quite liberal.

**Comment by dsperling** [comment]
@gottesmm can add more detail here, but the contribution guidelines for Swift appear to require Apache2.

https://github.com/apple/swift/blob/master/CONTRIBUTING.md

**Comment by gottesmm** [comment]
@mikeal Here is the issue:

1. I was going to try to include this in the swift benchmark suite. This is in the actual swift tree.
2. All code contributed to Swift must be under Apache2; IIRC a compatible license is not acceptable, but let me check that.

Now perhaps the right thing to do here is that we need a different "external project" test suite perhaps that can use projects with different licenses. Let me talk to some people.

Thank you for your help and quick response = ).

**Comment by mikeal** [comment]
Ya, it would be a pretty huge task to dual license.

MIT license doesn't have any virality so you can use the code in your tree without issue.

If I had to guess why you have a policy of requiring Apache2, it would be so that contributors to the code base opt into the patent provisions of the Apache2 license. If you aren't modifying the code in a significant way that shouldn't be an issue. If you do make large modifications, and want to ensure they fall under the Apache2 license, you would probably just end up making them locally and noting that the modifications fall under the Apache2 license and stick that copyright attribution and notice below the MIT notice already in the file.

**Comment by gottesmm** [comment]
@mikeal I have a few thoughts about the reasons why this is so, but I am trying not to speculate upon it.

**Comment by gottesmm** [comment]
The main reason AFAIK is that we are trying to keep the whole code base under the same license so we can have a simple consistent story around licensing (rather than having to say... this part of the tree is under this license and this other part of the tree is under a different license/etc).

**Comment by paulofaria** [comment]
Silly question. Are ports of a piece of software to a different language still required to be licensed under the original license?

**Comment by mikeal** [comment]
> Silly question. Are ports of a piece of software to a different language still required to be licensed under the original license?

If it's a re-implementation, no. Copyright governs the work itself so if you re-implement it would be a new work and could have a new license.

> The main reason AFAIK is that we are trying to keep the whole code base under the same license so we can have a simple consistent story around licensing (rather than having to say... this part of the tree is under this license and this other part of the tree is under a different license/etc).

I understand why you would want to do this for simplicity but in practice it ends up being rather difficult unless you are comfortable with pulling in a lot of external dependencies at build time. In the Node.js we've gone pretty much as far in the other direction as you could imagine and we check almost all of our dependencies into the tree. We have some automation that builds the main LICENSE file and calls out all the licenses and we keep pretty good track of any files that differ from the standard MIT license the rest of the project is under.

**Comment by dsperling** [comment]
Let me try to visually show what I did.  This is not a re-implementation, but rather a port of the original 'C' work, so the original license and copyrights should be maintained.  The goal was to maintain as much of the core logic as possible which will allow future 'C' fixes to be ported easily.  Here is an example:

https://github.com/nodejs/http-parser/blob/master/http_parser.c:
```
size_t http_parser_execute (http_parser *parser,
                            const http_parser_settings *settings,
                            const char *data,
                            size_t len)
{
  char c, ch;
  int8_t unhex_val;
  const char *p = data;
  const char *header_field_mark = 0;
  const char *header_value_mark = 0;
  const char *url_mark = 0;
  const char *body_mark = 0;
  const char *status_mark = 0;
  enum state p_state = (enum state) parser->state;
  const unsigned int lenient = parser->lenient_http_headers;

  /* We're in an error state. Don't bother doing anything. */
  if (HTTP_PARSER_ERRNO(parser) != HPE_OK) {
    return 0;
  }
  ...
```

https://github.com/smithmicro/HTTPParser/blob/master/Sources/HTTPParser/http_parser.swift:
```
public func execute (_ settings: http_parser_delegate,
              _ data: UnsafePointer<UInt8>,
              _ len: Int) -> Int
{
  var c, ch: UInt8
  var unhex_val: Int8 = 0
  var p: UnsafePointer<UInt8> = data
  var p_state = self.state
  let lenient = self.lenient_http_headers

  delegate = settings

  /* We're in an error state. Don't bother doing anything. */
  if (self.http_errno != .HPE_OK) {
    return 0
  }
  ...
```

Here is another example deeper in execute:

'C':
```
      case s_req_server:
      case s_req_server_with_at:
      case s_req_path:
      case s_req_query_string_start:
      case s_req_query_string:
      case s_req_fragment_start:
      case s_req_fragment:
      {
        switch (ch) {
          case ' ':
            UPDATE_STATE(s_req_http_start);
            CALLBACK_DATA(url);
            break;
          case CR:
          case LF:
            parser->http_major = 0;
            parser->http_minor = 9;
            UPDATE_STATE((ch == CR) ?
              s_req_line_almost_done :
              s_header_field_start);
            CALLBACK_DATA(url);
            break;
          default:
            UPDATE_STATE(parse_url_char(CURRENT_STATE(), ch));
            if (UNLIKELY(CURRENT_STATE() == s_dead)) {
              SET_ERRNO(HPE_INVALID_URL);
              goto error;
            }
        }
        break;
      }
```

Swift:
```
      case .s_req_server,
           .s_req_server_with_at,
           .s_req_path,
           .s_req_query_string_start,
           .s_req_query_string,
           .s_req_fragment_start,
           .s_req_fragment:

        switch (ch) {
          case ASCII_SPACE:
            p_state = .s_req_http_start
            if CALLBACK_DATA(p_state, p, .url) { return p - data + 1 }
            break
          case CR,
               LF:
            self.http_major = 0
            self.http_minor = 9
            p_state = (ch == CR) ?
              .s_req_line_almost_done :
              .s_header_field_start
            if CALLBACK_DATA(p_state, p, .url) { return p - data + 1 }
            break
          default:
            p_state = parse_url_char(p_state, ch)
            if (UNLIKELY(p_state == .s_dead)) {
              try SET_ERRNO(.HPE_INVALID_URL)
            }
        }
        break
```

I hope this helps explain the license and copyright dilemma.

The Node.js team has answered the original question regarding the dual-license request, so I will close this issue.

Thanks for your consideration.
