### ISSUE TITLE
Soname bumped on every version

### ISSUE THREAD

**Issue by AdamMajer** [nodejs/http-parser#345]
I notice that the soname is the entire version, and not just libhttp_parser.2 or similar. I see lots of soname bumps but ABI remains compatible. For example, the version 2.7.1 is marked as incompatible with version 2.7.0, while nothing really changed except minor bug fixes. Is there really no ABI compatibility guarantee between version updates of this library?

Is this intentional or a mistake?

**Comment by AdamMajer** [comment]
Closed #343 seems to bring up the same problem. Which means this is a bug... fixing.

**Comment by indutny** [comment]
There is ABI guarantee between patch versions, and it was totally a mistake during our release process. Thank you for bringing this up!
