### ISSUE TITLE
http/2.0 parser support  

### ISSUE THREAD

**Issue by billionling** [nodejs/http-parser#350]
Hi,

I find that you've got a plan about supporting http version 2 parser in closed issue.

Can you share your new repo?

**Comment by indutny** [comment]
Hello!

All work happens in https://github.com/nodejs/http2. It isn't going to use this repo for HTTP2 functionality.

Thanks,
Fedor.

**Comment by eLvErDe** [comment]
I'm sorry but the linked repo is nodejs itself. Is there anywhere http-parser, as a C library supporting HTTP/2.0 ?

Thanks

**Comment by bnoordhuis** [comment]
[nghttp2](https://nghttp2.org/) - it's what Node.js uses.
