### ISSUE TITLE
on_url did not parse http version ?

### ISSUE THREAD

**Issue by ldcsaa** [nodejs/http-parser#353]
after on_url triggered, both parser.http_major & parser.http_minor are still 0, until on_header triggered !!

**Comment by indutny** [comment]
This information is not available until `on_header` call. Here is how it looks like in plaintext:

```
GET /url HTTP/1.1
```

Sorry!

**Comment by ldcsaa** [comment]
then, does it better if on_url chang to on_request_line? all request info had been parsed including http version.

**Comment by indutny** [comment]
@ldcsaa `on_url` may be called several times for a single request if it will arrive in chunks. Even if we will call it `on_request_line`, the http version data won't be available until the first header or end of the message.

Please keep in mind that `http_parser` does not store any incoming data anywhere, and its state is just a few integer values.

**Comment by ldcsaa** [comment]
OK，thanks!!
