### ISSUE TITLE
why not support char '_' in host of http

### ISSUE THREAD

**Issue by hy05190134** [nodejs/http-parser#354]
http_parser_parse_url(url, url.length(), 0, &hp_u) 

like this "http://csy_push_stream.caifuzhinan.com/shipin/sunxi"

we find that if '_' is in the host of url, the func will return 1, not 0

**Comment by ploxiln** [comment]
This is probably because hostnames are not supposed to contain `_` aka underscore.
https://en.wikipedia.org/wiki/Hostname#Restrictions_on_valid_hostnames

**Comment by bnoordhuis** [comment]
What @ploxiln says, underscores aren't officially allowed in hostnames.  http-parser rejects them in strict mode (when compiled with `-DHTTP_PARSER_STRICT=1`) but accepts them in loose mode.
