### ISSUE TITLE
How to disable automatic chunks decoding?

### ISSUE THREAD

**Issue by povilasb** [nodejs/http-parser#362]
> The parser decodes the transfer-encoding for both requests and responses transparently. That is, a chunked encoding is decoded before being sent to the on_body callback.

Is it possible to configure parser not to decode chunked encoding?
I would like to receive chunks in `on_body` unmodified.

**Comment by bnoordhuis** [comment]
Stop feeding it data once the headers have been parsed?  If you're not interested in decoding, then there is no point in passing it to an on_body callback.

**Comment by povilasb** [comment]
I have a case where my server receives headers and body in one package:
```
b'HTTP/1.1 200 OK\r\nServer: nginx/1.11.6\r\nDate: Wed, 05 Apr 2017 12:59:38 GMT\r\nContent-Type: application/octet-stream\r\nTransfer-Encoding: chunked\r\nConnection: keep-alive\r\nContent-Range: bytes 0-29/30\r\nETag: range30\r\nAccept-Ranges: bytes\r\nAccess-Control-Allow-Origin: *\r\nAccess-Control-Allow-Credentials: true\r\n\r\n1e\r\nabcdefghijklmnopqrstuvwxyzabcd\r\n0\r\n\r\n'
```
So I feed this buffer only once to the parser.
And I don't know where the headers end, so I could split the body part.

**Comment by bnoordhuis** [comment]
Check the comment on the on_headers_complete callback in http_parser.h.  Return e.g. -1 to stop the parser from consuming the remainder of the buffer.
