### ISSUE TITLE
Upgrade header can be used to advertise protocol support

### ISSUE THREAD

**Issue by veesahni** [nodejs/http-parser#363]
Per RFC7230 (which supercedes 2616):

```
A server MAY send an Upgrade header field in any other response to
advertise that it implements support for upgrading to the listed
protocols, in order of descending preference, when appropriate for a
future request.
```

Accordingly, Apache advertises HTTP2 support with Upgrade headers in normal HTTP responses:

```
HTTP/1.1 200 OK
Date: Fri, 14 Apr 2017 03:08:10 GMT
Server: Apache
Upgrade: h2,h2c
Connection: Upgrade
Content-Length: 26
Content-Type: text/html; charset=utf-8
```

However, for such upgrade advertisements, http-parser thinks an upgrade is in progress and doesn't process the body.

If an Upgrade header is present in a 200 response, it should be ignored.  It's only an upgrade in a 101 response.

**Comment by bnoordhuis** [comment]
#364

**Comment by ploxiln** [comment]
fix was merged
