### ISSUE TITLE
Fails to build with gcc7 and -Werror

### ISSUE THREAD

**Issue by heirecka** [nodejs/http-parser#365]
http-parser fails to build with gcc7 and -Werror (which is passed by default) because of a new warning. I don't know the code to judge if it's intentional or not. In the former case there are attributes or comments to avoid the warning: https://gcc.gnu.org/onlinedocs/gcc/Warning-Options.html#index-Wimplicit

>  x86_64-pc-linux-gnu-cc
> 
>  -pipe -O2 -march=native -I. -DHTTP_PARSER_STRICT=0  -pipe -O2 -march=native -Wall -Wextra -Werror -O3  -c http
> _parser.c
> http_parser.c: In function 'http_parser_execute':
> http_parser.c:1817:31: error: this statement may fall through [-Werror=implicit-fallthrough=]
>                parser->upgrade = 1;
>                ~~~~~~~~~~~~~~~~^~~
> http_parser.c:1819:13: note: here
>              case 1:
>              ^~~~
> http_parser.c: In function 'http_parser_execute':
> http_parser.c:1817:31: error: this statement may fall through [-Werror=implicit-fallthrough=]
>                parser->upgrade = 1;
>                ~~~~~~~~~~~~~~~~^~~
> http_parser.c:1819:13: note: here
>              case 1:
>              ^~~~
> http_parser.c: In function 'http_parser_parse_url':
> http_parser.c:2376:18: error: this statement may fall through [-Werror=implicit-fallthrough=]
>          found_at = 1;
>          ~~~~~~~~~^~~
> http_parser.c:2379:7: note: here
>        case s_req_server:
>        ^~~~
> http_parser.c: In function 'http_parser_parse_url':
> http_parser.c:2376:18: error: this statement may fall through [-Werror=implicit-fallthrough=]
>          found_at = 1;
>          ~~~~~~~~~^~~
> http_parser.c:2379:7: note: here
>        case s_req_server:
>        ^~~~
> cc1: all warnings being treated as errors
> make: *** [Makefile:78: http_parser_g.o] Error 1
> make: *** Waiting for unfinished jobs....
> cc1: all warnings being treated as errors
> make: *** [Makefile:93: http_parser.o] Error 1

**Comment by misery** [comment]
https://github.com/nodejs/http-parser/pull/357

**Comment by ploxiln** [comment]
the fix in #357 was merged
