### ISSUE TITLE
http status callback is only invoked when http status text is received.

### ISSUE THREAD

**Issue by niecore** [nodejs/http-parser#373]
It is not mandatory to send the http status text with the http status code.
The callback is only called as soon as the http status text is received.

Some servers, i.e. "nginx" doesn't transmit the http status text in all cases. This results in that no callback is called.

**Comment by bnoordhuis** [comment]
`.on_status` is a data callback, it doesn't really make sense to call it without data.

**Comment by ploxiln** [comment]
This appears to be related to #367.

The `on_status` callback is not what actually delivers the status code, but programs may have used it to know as soon as the status code is available, so it's arguably a change in behavior ... but these responses were not parsed at all before anyway ...

**Comment by niecore** [comment]
Ok, both of you are right.
A workaround would be to read out the status code in the .on_headers_complete cb.
I think the issue can be closed since this problem has been discussed already.
