### ISSUE TITLE
Request new release: v2.7.1, does not build with gcc 7.1.1 due to FALLTHROUGH issue

### ISSUE THREAD

**Issue by WilCrofter** [nodejs/http-parser#381]
Although the FALLTHROUGH issue was fixed in [0852bea](https://github.com/nodejs/http-parser/commit/0852bea482e0842b0445c14b19dc9b318a6c4eba) the last release predates the fix.

v2.7.1 is currently a dependency of [JuliaWeb/HttpParser.jl](https://github.com/JuliaWeb/HttpParser.jl) which will, of course, not build with current versions of gcc.

**Comment by bnoordhuis** [comment]
@indutny Maybe you can do a release?

**Comment by ploxiln** [comment]
BTW the obvious future-proofing fix here is to get rid of `-Werror` which really is a bad idea for exactly this reason. (You can use it for building for tests, but not for actual use.)

Another more robust fix is to acknowledge that no serious project uses the chronically unmaintained Makefile in this repo, they just incorporate the nice single .c/.h pair into their own build system (and if they have any sense they don't use `-Werror` outside of tests).

This is a C library, it should keep compatibility with tools and other libraries for more than 6 months at a time!

**Comment by craig65535** [comment]
Hi, I am involved in a serious project and we use the provided Makefile (`make CFLAGS=... package`). This allows us to cleanly separate our third-party dependencies from our own code base. We do

**Comment by bnoordhuis** [comment]
v2.8.0 has been released today and contains the fix.
