### ISSUE TITLE
Request for information about the schedule of next release

### ISSUE THREAD

**Issue by sachinHPrabhu** [nodejs/http-parser#382]
The master branch of the http-parser project already has a fix that I am interested in.

Tolerate non-compliant status line responses 
https://github.com/nodejs/http-parser/commit/3b0da34d83e4eace29cc49e3b659bf630537b94c

Hence I wished to know if there is any schedule for next release of the http-parser.

Thanking You.
Regards.

**Comment by Leont** [comment]
+1

**Comment by indutny** [comment]
Welcome to "Release-by-demand" service, please enjoy freshly baked 2.8.0 :wink:

(Sorry for delay, I'm glad that you asked for it!)

**Comment by bnoordhuis** [comment]
@indutny Did something go wrong?  I don't see the new tag or changes to the version number.

**Comment by indutny** [comment]
Oh gosh, it did. There was an extra commit in a `master` that I didn't pull (guess what), and I didn't bother to check the console output before reporting here. Sorry, everyone! It should be right now!

**Comment by sachinHPrabhu** [comment]
Thanks a lot for the release v2.80.
