### ISSUE TITLE
Those URL can't be recognized by parse_url_char

### ISSUE THREAD

**Issue by tianchao-haohan** [nodejs/http-parser#383]
Use the latest v2.7.1 as the http parser.

From the image below, those url contains escape character can't be parsed successfully.
![empty_uri](https://user-images.githubusercontent.com/8639363/29994517-e79c91ea-9003-11e7-95d5-3d3b436c110e.png)

**Comment by ploxiln** [comment]
non-ascii bytes cannot be in a URL path or query, they must be url-encoded
http://www.blooberry.com/indexdot/html/topics/urlencoding.htm

**Comment by tianchao-haohan** [comment]
Is there workaround if there are some non-ascii bytes in url? for example, encode those non-ascii bytes.

**Comment by tianchao-haohan** [comment]
@ploxiln I think it is reasonable that support the utf-8 bytes in url. So, we can find out what urls are using non-ascii bytes.

**Comment by tianchao-haohan** [comment]
Can somebody help me on this problem? Please give me some tips on how to do then enhancement.

**Comment by bnoordhuis** [comment]
Compile http_parser in non-strict mode and it will accept bytes > 127 (and, by extension, UTF-8.)
