### ISSUE TITLE
When parsing response that omits status message text, on_status is never called

### ISSUE THREAD

**Issue by TechnikEmpire** [nodejs/http-parser#384]
On status callback does not get invoked when we're dealing with a web server that omits the status text from the status line. Examples of servers doing this are kijiji.

Example from in the wild:
```
GET 
https://www.kijiji.ca/h-lloydminster-ab/1700095

Status: HTTP/1.1 200
```

Server is advertised as being nginx.

When parsing the response, `on_status` will never be called. Not sure if this is intended or not, I started looking into the spec for this and didn't see any `MUST`'s with regards to the status text. I came up with a solution to work around this personally so I don't care anymore, just FYI.

**Comment by TechnikEmpire** [comment]
Worth mentioning that the parser does not fail nor complain of errors, it just silently omits invoking the callback. When you check the status code and http version etc later it is indeed present and parsed correctly.

**Comment by ploxiln** [comment]
related to #367 
(I think it makes sense not to call `on_status`, which provides bytes of the status string, since there are no such bytes. You can check the code in `on_headers_complete`.)

**Comment by sachinHPrabhu** [comment]
In the old tag that our org is using, the statuscode is still zero when on_headers_complete gets called.

The fix is in master for this issue.
Tolerate non-compliant status line responses
 https://github.com/nodejs/http-parser/commit/3b0da34d83e4eace29cc49e3b659bf630537b94c 

Waiting for next tag.
Cheerz.

**Comment by bnoordhuis** [comment]
v2.8.0 has been released today and includes the fix.  I'll close this out.
