### ISSUE TITLE
http response body can't be totally parsed

### ISSUE THREAD

**Issue by tianchao-haohan** [nodejs/http-parser#387]
2017-09-21 19:48:16 [thread:10505] DEBUG (line=534, func=on_message_complete): tid:10505 on_message_complete
2017-09-21 19:48:16 [thread:10505] DEBUG file=http_analyzer.c (line=369, func=on_message_begin): tid:10505, 
2017-09-21 19:48:16 [thread:10505] DEBUG file=http_analyzer.c (line=371, func=on_message_begin): tid:10505

Another problem is that http response was partially parsed. The totally bytes of http response is 744. 580 bytes of the http response was parsed. Part of the parsed content is: 
HTTP/1.1 404 Not Found
Server: Tengine
Date: Thu, 21 Sep 2017 11:48:16 GMT
Content-Type: text/htq

And part of the un-parsed content : 
<tr>
<td>Server:</td>
<td>lb1

**Comment by bnoordhuis** [comment]
This is too incomplete to be actionable.  Can you post steps to reproduce?

**Comment by tianchao-haohan** [comment]
@bnoordhuis Thanks. I agree with you that more information is needed. But could you please tell me what information should be collected, is that the whole http response?

**Comment by bnoordhuis** [comment]
The response would be a good first step, yes.

**Comment by tianchao-haohan** [comment]
HTTP/1.1 301 Moved Permanently
Server: Tengine
Date: Sun, 24 Sep 2017 20:48:53 GMT
Content-Type: text/html
Content-Length: 278
Connection: keep-alive
Location: https://www.starwin.com/

<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html>
<head><title>301 Moved Permanently</title></head>
<body bgcolor="white">
<h1>301 Moved Permanently</h1>
<p>The requested resource has been assigned a new permanent URI.</p>
<hr/>Powered by Tengine</body>
</html>

**Comment by tianchao-haohan** [comment]
**Case2:** (the response body is same as Case1, but stopped at different place.
```
HTTP/1.1 301 Moved Permanently^M
Server: Tengine^M
Date: Mon, 25 Sep 2017 00:05:16 GMT^M
Content-Type: text/html^M
Content-Length: 278^M
Connection: keep-alive^M
Location: https://www.starwin.com/^M
^M
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">^M
<html>^M
<head><title>301 Moved Permanently</title></head>^M
<body bgcolor="white">^M
<h1>301 Moved Permanently</h1>^M
<p>The requested resource has been assigned a new permanent URI.</p>^M
<hr/>Powered by Tengine</body>^M
</html>^M
```
*****************
remains:
```
ermanently</title></head>^M
<body bgcolor="white">^M
<h1>301 Moved Permanently</h1>^M
<p>The requested resource has been assigned a new permanent URI.</p>^M
<hr/>Powered by Tengine</body>^M
</html>^M
```

**Comment by tianchao-haohan** [comment]
**Case3:**
```
HTTP/1.1 200 ^M
Server: Tengine^M
Date: Mon, 25 Sep 2017 00:12:26 GMT^M
Content-Type: application/json;charset=UTF-8^M
Transfer-Encoding: chunked^M
Connection: keep-alive^M
Vary: Accept-Encoding^M
X-B3-Sampled: 1^M
X-B3-SpanId: 9011a762c94b1cee^M
X-B3-TraceId: 9011a762c94b1cee^M
X-Application-Context: starwin-service^M
Content-Encoding: gzip^M
^M
21f^M
^_<8b>^H^@^@^@^@^@^@^Ce<93>Án^Z1^P<86>_%²<94>^[ {a<97>À<8d>^R<90>PQ<8a><80>ô^REÈ]&Ô<8d>×^Ù^
BHQO½¥·öÖSÏ=¶}<9f>&}<8d><8e>ÙÝfS$¤Õ|3ó{ü^OÞ<91>X+^GÊ<91>î<8e>Hañ{µ#bIº<8c>²^ZQ<^AÒ%<8f>_¾>|úøûçÝÃý^O<82>T#c<8c>R<86>^AlR^G±<9b>^X}#°<9b><84>§u^V<9e>b"Î<92>Lr'ÖÐKtæO8k6Ã<88>RZÍõóT<9b>6«´TÃR)^RáJ^E<<93>^^^D^R¾)<99>Ê¤¬^Q¡b^CÜBµ²Fø<9a>^KÉßH8^RH<8b>^SBvF£FÔ*É^DL|°<83>6(ë´[^QN ãÛs¾%Ý^NÍ<83>ù6õ®^L/ÇãÅøUÿ%^Ö:î2<8b>pt±<98>öF³^A2<97><97>M¦£×½ù`1¼¼8GÊÓTn§<99><84>rrË%Tã¼<80>;ßKI<91>ÏÃ^F¥!^R#ìí^XÖ Ë<8a>·ú}îØ\äûú~ÿøù[Ðúóá×aCÂ^M¡Ð ^^Cý[%ÏXP#ï´PO^HÇ×<8e>ËÉ<91>M^Uü¯»0ÊÀ^R A<8d>Á^F<92>Ô   ­Ð64¥^YQ¿ ëL^V{ZÞ4w¼Ïe|X»V£ã^Z¥^]Ø2¸^Q<8a>«X¨ÕÌqS\ö¿Ì@-«\¨5X<87>ü^E¬^D<8e>ã<8e>3ØQå<86>^K^K³,<8e>ÁÚ*<97>Üº^Y8'!ÁÿG_'©^D^GE+ (k×i§^^^D'^AíRÿ#~*Sm*¶<83>µQ<9d>²zà<9f>ÏsÙ§<8a>\<8d><9d>°°PÛ_ï½Ã6<93>þ<95>Ù|@¿]c´A<87>®®ñ^Aée1ïþ/<9c>^]Ó^GÙ^C^@^@^M
0^M
^M
```
*****************
remains:
```
^Uü¯»0ÊÀ^R A<8d>Á^F<92>Ô    ­Ð64¥^YQ¿ ëL^V{ZÞ4w¼Ïe|X»V£ã^Z¥^]Ø2¸^Q<8a>«X¨ÕÌqS\ö¿Ì@-«\¨5X<87>ü^E¬^D<8e>ã<8e>3ØQå<86>^K^K³,<8e>ÁÚ*<97>Üº^Y8'!ÁÿG_'©^D^GE+ (k×i§^^^D'^AíRÿ#~*Sm*¶<83>µQ<9d>²zà<9f>ÏsÙ§<8a>\<8d><9d>°°PÛ_ï½Ã6<93>þ<95>Ù|@¿]c´A<87>®®ñ^Aée1ïþ/<9c>^]Ó^GÙ^C^@^@^M
0^M
```

**Comment by tianchao-haohan** [comment]
**Case4:**
```
HTTP/1.1 302 Moved Temporarily^M
Server: Tengine^M
Date: Mon, 25 Sep 2017 00:10:06 GMT^M
Content-Type: text/html^M
Content-Length: 258^M
Connection: keep-alive^M
Location: http://forum.dabo.com/^M
Access-Control-Allow-Origin: *^M
^M
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">^M
<html>^M
<head><title>302 Found</title></head>^M
<body bgcolor="white">^M
<h1>302 Found</h1>^M
<p>The requested resource resides temporarily under a different URI.</p>^M
<hr/>Powered by Tengine</body>^M
</html>^M
```
*****************
remains:
```
//DTD HTML 2.0//EN">^M
<html>^M
<head><title>302 Found</title></head>^M
<body bgcolor="white">^M
<h1>302 Found</h1>^M
<p>The requested resource resides temporarily under a different URI.</p>^M
<hr/>Powered by Tengine</body>^M
</html>^M
```

**Comment by tianchao-haohan** [comment]
Case5:
```
HTTP/1.1 200 OK^M
Server: Tengine^M
Date: Mon, 25 Sep 2017 00:11:07 GMT^M
Content-Type: text/html; charset=UTF-8^M
Connection: keep-alive^M
Vary: Accept-Encoding^M
X-Pingback: http://www.dabo.com/caifu/xmlrpc.php^M
Link: <http://www.dabo.com/caifu/wp-json/>; rel="https://api.w.org/"^M
^M
```
*****************
remains:
```
 25 Sep 2017 00:11:07 GMT^M
Content-Type: text/html; charset=UTF-8^M
Connection: keep-alive^M
Vary: Accept-Encoding^M
X-Pingback: http://www.dabo.com/caifu/xmlrpc.php^M
Link: <http://www.dabo.com/caifu/wp-json/>; rel="https://api.w.org/"^M
```

**Comment by tianchao-haohan** [comment]
Case6:
```
HTTP/1.1 404 Not Found^M
Server: Tengine^M
Date: Mon, 25 Sep 2017 00:11:00 GMT^M
Content-Type: text/html; charset=utf-8^M
Content-Length: 579^M
Connection: keep-alive^M
^M
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">^M
<html>^M
<head><title>404 Not Found</title></head>^M
<body bgcolor="white">^M
<h1>404 Not Found</h1>^M
<p>The requested URL was not found on this server. Sorry for the inconvenience.<br/>^M
Please report this message and include the following information to us.<br/>^M
Thank you very much!</p>^M
<table>^M
<tr>^M
<td>URL:</td>^M
<td>http://www.starlinked.com/</td>^M
</tr>^M
<tr>^M
<td>Server:</td>^M
<td>lb101.sl.com</td>^M
</tr>^M
<tr>^M
<td>Date:</td>^M
<td>2017/09/25 08:11:00</td>^M
</tr>^M
</table>^M
<hr/>Powered by Tengine</body>^M
</html>^M
```
*****************
remains:
```
<tr>^M
<td>Server:</td>^M
<td>lb101.sl.com</td>^M
</tr>^M
<tr>^M
<td>Date:</td>^M
<td>2017/09/25 08:11:00</td>^M
</tr>^M
</table>^M
<hr/>Powered by Tengine</body>^M
</html>^M
```

**Comment by tianchao-haohan** [comment]
@bnoordhuis ,Is those information above enough for triage?

**Comment by bnoordhuis** [comment]
@tianchao-haohan Thanks for the updates.  Can you post or link your code that interacts with http-parser?

**Comment by tianchao-haohan** [comment]
It seems that the problem was gone recently. I'm not sure what change caused this. From your comments, it seem that the problem cause by the inappropriate usage of http_parser. 
Here is the code snippet about how to use http_parser:
        parseCount = http_parser_execute (&currSessionDetail->reqParser,
                                          &currSessionDetail->reqParserSettings,
                                          (const char *) data, dataLen);

    /* Init http request parser */
    reqParser = &hsd->reqParser;
    reqParserSettings = &hsd->reqParserSettings;
    memset (reqParserSettings, 0, sizeof (*reqParserSettings));
    reqParserSettings->on_message_begin = onReqMessageBegin;
    reqParserSettings->on_url = onReqUrl;
    reqParserSettings->on_header_field = onReqHeaderField;
    reqParserSettings->on_header_value = onReqHeaderValue;
    reqParserSettings->on_headers_complete = onReqHeadersComplete;
    reqParserSettings->on_body = onReqBody;
    reqParserSettings->on_message_complete = onReqMessageComplete;
    http_parser_init (reqParser, HTTP_REQUEST);

    /* Init http response parser */
    resParser = &hsd->resParser;
    resParserSettings = &hsd->resParserSettings;
    memset (resParserSettings, 0, sizeof (*resParserSettings));
    resParserSettings->on_message_begin = onRespMessageBegin;
    resParserSettings->on_url = onRespUrl;
    resParserSettings->on_header_field = onRespHeaderField;
    resParserSettings->on_header_value = onRespHeaderValue;
    resParserSettings->on_headers_complete = onRespHeadersComplete;
    resParserSettings->on_body = onRespBody;
    resParserSettings->on_message_complete = onRespMessageComplete;
    http_parser_init (resParser, HTTP_RESPONSE);

**Comment by tianchao-haohan** [comment]
```
GET .\.\.\.\.\.\.\.\.\.\/winnt/win.ini HTTP/1.1^M
Host: 10.16.74.240^M
Accept-Charset: iso-8859-1,utf-8;q=0.9,*;q=0.1^M
Accept-Language: en^M
Connection: Keep-Alive^M
User-Agent: Mozilla/4.0 (compatible; MSIE 8.0; Windows NT 5.1; Trident/4.0)^M
Pragma: no-cache^M
Accept: image/gif, image/x-xbitmap, image/jpeg, image/pjpeg, image/png, */*^M
```

remains:
```
.\.\.\.\.\.\.\.\.\.\/winnt/win.ini HTTP/1.1^M
Host: 10.16.74.240^M
Accept-Charset: iso-8859-1,utf-8;q=0.9,*;q=0.1^M
Accept-Language: en^M
Connection: Keep-Alive^M
User-Agent: Mozilla/4.0 (compatible; MSIE 8.0; Windows NT 5.1; Trident/4.0)^M
Pragma: no-cache^M
Accept: image/gif, image/x-xbitmap, image/jpeg, image/pjpeg, image/png, */*^M
```

**Comment by bnoordhuis** [comment]
`.\.\.\.\.\.\.\.\.\.\/winnt/win.ini` is not a valid request path.  Check that `HTTP_PARSER_ERRNO(parser) == HPE_OK` after `http_parser_execute()` returns.  If it isn't, you should close the connection.

I'll close this out.  Let me know if there is reason to believe it's a http-parser bug after all.
