### ISSUE TITLE
Copyright violation: Based on BSD-licensed code, but no BSD license or original copyright statements

### ISSUE THREAD

**Issue by julian-klode** [nodejs/http-parser#389]
http_parser.c states:

```
Based on src/http/ngx_http_parse.c from NGINX copyright Igor Sysoev
```

nginx has the following license and copyright statement in its license file:

```

/* 
 * Copyright (C) 2002-2013 Igor Sysoev
 * Copyright (C) 2011-2013 Nginx, Inc.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 * 1. Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 * 2. Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in the
 *    documentation and/or other materials provided with the distribution.
 *
 * THIS SOFTWARE IS PROVIDED BY THE AUTHOR AND CONTRIBUTORS ``AS IS'' AND
 * ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
 * ARE DISCLAIMED.  IN NO EVENT SHALL THE AUTHOR OR CONTRIBUTORS BE LIABLE
 * FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
 * DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
 * OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
 * HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
 * OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
 * SUCH DAMAGE.
 */
```

The license requires itself and the copyright statements to be retained, neither of which is happening. This project is therefore not legally reproducible as-is.

**Comment by ploxiln** [comment]
Just for convenient reference, the commit which introduces the version theoretically based on nginx code, from November 2009: 433202d825fa34de5e42f810bb984ece05a36d20

**Comment by ploxiln** [comment]
just another convenient reference, commit adding (some) nginx attribution: 8dabce6ec7142319bc5c883ff53bf7302f0d83ce

**Comment by bnoordhuis** [comment]
I don't know if any nginx code remains.  If anyone can point out examples, please do so and I'll update the license.  Otherwise we should probably just remove the attribution to avoid confusion.

The only code that was taken verbatim from nginx that I'm aware of were some lookup tables and a couple of macros but they were removed in 2010.

**Comment by indutny** [comment]
I believe that there might not be any common lines between them anymore. Let's remove this unless there are objections.

**Comment by ploxiln** [comment]
just for convenient reference:

another commit "use nginx-style method compare" https://github.com/nodejs/http-parser/commit/4bce6b44670e6effb9246f407654721f756fa4c7 (though I'm pretty sure all that code is replaced by now)

commit "use lookup tables of my own" which removes an attribution to nginx: https://github.com/nodejs/http-parser/commit/6f12467a8af7c365c5d072e3b5456a5c4159957a

**Comment by ploxiln** [comment]
last relevant reference: ngx_http_parce.c from nginx-0.7.64 in November 2009: https://github.com/nginx/nginx/blob/a49413511aa15ecc50755be2ff01d785b722e017/src/http/ngx_http_parse.c

**Comment by bnoordhuis** [comment]
#390
