### ISSUE TITLE
Was connect supported in http_parser?

### ISSUE THREAD

**Issue by tianchao-haohan** [nodejs/http-parser#392]
```
CONNECT www.youku.com:443 HTTP/1.0^M
User-Agent: Mozilla/5.0 (Windows NT 6.3; WOW64; Trident/7.0; Touch; MALCJS; rv:11.0) like Gecko^M
Host: www.youku.com:443^M
Content-Length: 0^M
DNT: 1^M
Proxy-Connection: Keep-Alive^M
Pragma: no-cache^M
```
returns:
Request -- Upgrade header was present and the parser has exited because of that

**Comment by bnoordhuis** [comment]
CONNECT is supported.  You basically need to check that`req->method == HTTP_CONNECT`.

If something isn't working for you, can you be more specific?  Maybe post example code?

**Comment by tianchao-haohan** [comment]
Thanks your response. I will post the example if the problem reproduced.
