### ISSUE TITLE
http-parser does not remove trailing OWS after header field value

### ISSUE THREAD

**Issue by tatsuhiro-t** [nodejs/http-parser#393]
Quoted from https://tools.ietf.org/html/rfc7230#section-3.2.4

>    A field value might be preceded and/or followed by optional
   whitespace (OWS); a single SP preceding the field-value is preferred
   for consistent readability by humans.  The field value does not
   include any leading or trailing whitespace: OWS occurring before the
   first non-whitespace octet of the field value or after the last
   non-whitespace octet of the field value ought to be excluded by
   parsers when extracting the field value from a header field.

The following test case fails:

```c
#define TRAILING_OWS 42
, {.name = "trailing OWS"
  ,.type= HTTP_REQUEST
  ,.raw= "GET / HTTP/1.1\r\n"
         "Host: example.com     \r\n"
         "\r\n"
  ,.should_keep_alive= TRUE
  ,.message_complete_on_eof= FALSE
  ,.http_major= 1
  ,.http_minor= 1
  ,.method= HTTP_GET
  ,.request_path=  "/"
  ,.request_url= "/"
  ,.query_string= ""
  ,.fragment= ""
  ,.num_headers= 1
  ,.headers= { { "Host", "example.com" } }
  ,.body= ""
}
```

```
*** Error: header value in 'trailing OWS' ***

expected 'example.com'
   found 'example.com     '
```

**Comment by bnoordhuis** [comment]
That's intentional, you just have to deal with it.  It falls out from http-parser's design.

To explain, http-parser reports start and end to callbacks.  The input might be split across buffers.  If it sees the `\r\n` but the last non-ws character is in a previous buffer, boom - no way to report.

**Comment by tatsuhiro-t** [comment]
Thank you for reply.  I understand that.
