### ISSUE TITLE
New release needed: 2.7.1 http_parser.h does not contain HTTP_STATUS_MAP

### ISSUE THREAD

**Issue by tduehr** [nodejs/http-parser#394]
This is needed by tang.

see also: https://github.com/latchset/tang/issues/19

**Comment by Leont** [comment]
Yes a new release with `HTTP_STATUS_MAP` would be helpful

**Comment by bnoordhuis** [comment]
v2.8.0 was released today.

**Comment by sachinHPrabhu** [comment]
Thanks a lot for the release v2.8.0
