### ISSUE TITLE
Support for `SOURCE` method

### ISSUE THREAD

**Issue by bradisbell** [nodejs/http-parser#405]
A Feature Request:  As it is difficult to add support for custom methods, and the chatter on the various issue reports for it over the years indicates that "just use HTTP/2" is the final solution, could a `SOURCE` method be added as a possible HTTP method?

This method has been in-use by streaming media servers for a little over 15 years, and is still the dominant technology used for live HTTP progressive streaming source clients.  Most source clients cannot be configured to use `PUT` or another method, so servers supporting this type of streaming media must support `SOURCE`.

The [current workaround](https://stackoverflow.com/a/24298059/362536) involves some really nasty duck punching, which has to be updated regularly since it fiddles with Node.js internals on the JavaScript side.  Proper support for `SOURCE` would be greatly appreciated.  Thank you!

**Comment by bnoordhuis** [comment]
Pull requests welcome, see e557b62744e4f487a303b25b27c56947d7a8bacc for an example.  Note that the new method should go at the end of the method map.
