### ISSUE TITLE
100 continue support?

### ISSUE THREAD

**Issue by alyssawilk** [nodejs/http-parser#406]
I could be misreading / mistesting the code but it looks to me as if http-parser currently doesn't handle 100-continue.

I believe by the spec if a request is sent with Expect: 100-continue a response of the form

HTTP/1.1 100 Continue\r\n\r\n
....
HTTP/1.1 200 OK
... normal headers and body

is valid and http-parser should pass both sets of headers up to the caller with on_headers_complete.  I think that would require  http-parser to check on the response code state and rewind from s_headers_done after passing headers up to the caller.

Would you folks be amenable to a PR adding said support?

If so, please send any early design suggestions you think are appropriate.  I'd be fine with this off by default, or having a separate callback to avoid multiple on_headers_complete calls.  Whatever works!

**Comment by bnoordhuis** [comment]
http-parser never backtracks; it can't because the data might be in a different chunk.

> http-parser should pass both sets of headers up to the caller with on_headers_complete.

http-parser reports them as separate responses.  If it squelched the 100 response you wouldn't be able to tell if it's safe to send the request body.

**Comment by alyssawilk** [comment]
Hm, by the spec they're one response but I'll buy it's probably easier for callers to squelch the message complete callback and reset their own internal state than do special request handling so it's probably not worth the code complexity of the dual call up.  Thanks for the explanation and I'll drop the request.
