### ISSUE TITLE
Supporting mildly-broken clients and/or ICE/1.0

### ISSUE THREAD

**Issue by bradisbell** [nodejs/http-parser#410]
Icecast source clients are essentially HTTP/1.0 clients, except that they have one key difference in the request line for requests.  Instead of `HTTP/1.0`, they have `ICE/1.0`.  For example:

    SOURCE /brad/mp3-256k ICE/1.0

The rest of the request and behavior are normal HTTP/1.0.  It would be beneficial to many if we could handle somewhat-broken requests like these, if they are recoverable.  I think there are a few possible paths:

## Handle ICE/1.0 explicitly

I think this would involve adding states for `s_req_http_I`, `s_req_http_IC`, `s_req_http_ICE`, and then setting `parser->http_major = 1` and `parser->http_minor = 0`, similar to the way HTTP/0.9 clients work.  https://github.com/nodejs/http-parser/blob/master/http_parser.c#L1085

## Don't enforce literal 'HTTP' string in request line

If the parser were to simply look for the next slash `/` and a version, and if the request line were otherwise well-formed, we could support `ICE/1.0` as well as other mildly-broken clients.

## Allow an application-level hook for status line parsing or re-writing

If the application using the parser could either parse the request line on its own when `\r\n` is first hit, or if the application could re-write the line before the parser parses it, these sorts of oddball use cases could be handled.

Any thoughts on this enhancement?  Thank you.

**Comment by bnoordhuis** [comment]
I discussed it with Brad over email and I'd be fine with allowing ICE unconditionally or when the request method is SOURCE.

@indutny Thoughts?

**Comment by bnoordhuis** [comment]
https://github.com/nodejs/http-parser/pull/431
