### ISSUE TITLE
How do you install this package in Ubuntu 

### ISSUE THREAD

**Issue by ilanoh** [nodejs/http-parser#415]
It is not described in your read me, thank you

**Comment by styfle** [comment]
It's described on the website under "Debian and Ubuntu based Linux distributions":

https://nodejs.org/en/download/package-manager/#debian-and-ubuntu-based-linux-distributions

```
curl -sL https://deb.nodesource.com/setup_8.x | sudo -E bash -
sudo apt-get install -y nodejs
```
