### ISSUE TITLE
Inside on_url cb http protocol version is always 0

### ISSUE THREAD

**Issue by shaolin** [nodejs/http-parser#417]
Hi,

executing the following code in every cb, you can see that http_parser::http_major and http_parser::http_minor are always 0 inside on_url callback.

`void dumpHttpParserInfo(http_parser* p){

    auto method = http_method_str(http_method(p->method));
    auto errorName = http_errno_name(http_errno(p->http_errno));
    auto errorDescription = http_errno_description(http_errno(p->http_errno));

    cout << "METHOD:\t" << string_view(method) << endl
         << "HTTP:\t" << to_string(p->http_major) << "." << to_string(p->http_minor) << endl
         << "ERROR:\t" << string_view(errorName) << " - " << string_view(errorDescription) << endl;

};`

Is it normal?

Tahnks,

Dario

**Comment by indutny** [comment]
That's normal because URL is parsed before the protocol version when applying parser to HTTP requests.

**Comment by shaolin** [comment]
OK, so I close this issue.

Thank you very much

**Comment by indutny** [comment]
No problem.
