### ISSUE TITLE
Not able to set up callbacks in member function of object in c++.

### ISSUE THREAD

**Issue by biradarganesh25** [nodejs/http-parser#421]
I'm not able to set function call backs in member function of an object. It is not able to cast the type correctly. The callbacks are defined in the same file as the member definition. The settings variable is local to the member function.  [This](https://github.com/nodejs/http-parser/blob/master/http_parser.h) is my header. And [this](https://pastebin.com/nX47e7S8) is my implementation file. 

I have defined the callbacks in the implementation file and tried to set up the call backs in the member function getRequest in the implementation file, but it is giving me this error : 

```
HttpParser.cpp:153:27: error: cannot convert ‘HttpParser::header_field_cb’ from type ‘int (HttpParser::)(http_parser*, const char*, size_t) {aka int (HttpParser::)(http_parser*, const char*, long unsigned int)}’ to type ‘http_data_cb {aka int (*)(http_parser*, const char*, long unsigned int)}’
  settings.on_header_field = header_field_cb;
```
Please help me fix this. Thank you.

**Comment by bnoordhuis** [comment]
Simple:

1. Store object pointer in `.data` field.
2. Call appropriate method in callback.

I'm closing this out because it's basically about C++ trivia, not something that is specific to http_parser.

**Comment by Falven** [comment]
Just wanted to say thanks for the comment @bnoordhuis after reading it a couple of timers I understood what you were saying.

Use the `http_parser` struct's `data` field which is a `void *` to store a reference to your class instance (`this`), that you can then use [when mapping the C++ member functions to the C callbacks](https://stackoverflow.com/questions/36666608/map-c-member-function-to-c-callback).
