### ISSUE TITLE
Support more URL types in URL parser (Discussion)

### ISSUE THREAD

**Issue by eintw1ck** [nodejs/http-parser#433]
Is there a particular reason that the url parser from http-parser doesnt support `file:///file/urls/` or just not implemented yet? (also unix socket urls like `unix:/tmp/my.sock`).
I guess the first requires the parser to allow empty hosts, and the second needs to allow empty hosts and no double slash requirement, though I'm not sure what you'd want to do here. The `is_connect` argument could be changed to be a more generic flag argument (while still keeping backward compat).

**Comment by bnoordhuis** [comment]
It only needs to parse URLs that you'd encounter in a HTTP request.  Thanks for the suggestion but at this point extending the range of accepted inputs can only introduce security holes in existing applications.

**Comment by eintw1ck** [comment]
> It only needs to parse URLs that you'd encounter in a HTTP request.

I can understand that a lot of current users may not need this behavior, but requiring it to be enabled with a flag solves this.

>Thanks for the suggestion but at this point extending the range of accepted inputs can only introduce security holes in existing applications.

Why **must** there be more security holes? The code added doesn't have to add extra security holes if you just don't write them.

The main reason I want this exact project to support parsing a wider set of URLs is that the HTTP parser is actually pretty good, and it'd be a shame to have to pull in another dependency to pass only _URLs_.

**Comment by bnoordhuis** [comment]
> Why must there be more security holes? The code added doesn't have to add extra security holes

You misunderstand.  I'm not talking about holes in the parser but in applications that don't expect it to accept inputs it didn't accept before.

Overloading the `is_connect` argument with more options won't do any good because for all we know there might be programs that pass in `-1`.

**Comment by eintw1ck** [comment]
> Overloading the is_connect argument with more options won't do any good because for all we know > there might be programs that pass in -1.

I guess this is a fair explanation. I also assume you'd be adverse to a `http_parser_parse_url2()` function which there was a compatibility `http_parser_parse_url()` wrapper around?

**Comment by bnoordhuis** [comment]
I won't block it outright if that is what you mean, maybe another maintainer finds it useful, but personally I don't think it's an issue that needs solving in http_parser.
