### ISSUE TITLE
The http request can't be totally parsed

### ISSUE THREAD

**Issue by tianchao-haohan** [nodejs/http-parser#442]
Here is the request content:
```
POST /xxxapi/agent/new-index HTTP/1.1
User-Agent: appVersion=2.4.15,devType=android
: 
Content-Length: 26
Content-Type: application/x-www-form-urlencoded; charset=UTF-8
Host: test.tomcat.com
Connection: Keep-Alive
Accept-Encoding: gzip,deflate
```

The parser finished at the position of 86 ( the end of 'android').
And "CALLBACK_DATA(header_field)" was not triggered for "User-Agent".

**Comment by tianchao-haohan** [comment]
The issue could be fixed by the following workaround:
```
1178       case s_header_field_start:
1179       {
1180           if (ch == ':') {
1181               while (*p != CR && *p != LF) p++;
1182               while (*p == CR || *p == LF) p++;
1183               ch = *p;
1184               REEXECUTE();
1185           }
1186         if (ch == CR) {
1187           UPDATE_STATE(s_headers_almost_done);
1188           break;
1189         }
```

**Comment by indutny** [comment]
Hello!

I'm afraid that the HTTP request from your message above isn't valid according to the spec. This is likely a won't fix in this library, unless such requests are very common.

**Comment by tianchao-haohan** [comment]
@indutny I agree with you that the message isn't valid according to the spec. However, there will be many kinds of curious usage in the reality. And web server didn't report error to this scenario.

**Comment by bnoordhuis** [comment]
Thanks for the bug report but, since http-parser is working as expected here, I'm going to close it out.
