### ISSUE TITLE
assert(!messages[num_messages].message_begin_cb_called);

### ISSUE THREAD

**Issue by jiamuluo** [nodejs/http-parser#449]
my application is running by sisngle thread ,so i defines tatic struct message messages[1];.every time i need parse http data,i will  do that 
num_messages = 0;
bzero(messages,sizeof(messages)); ,
messages[num_messages].message_begin_cb_called = FALSE;,
http_parser_init(parser, HTTP_BOTH);
http_parser_execute(parser, &settings, data, slDataLen);

But i always exit caused by assert(!messages[num_messages].message_begin_cb_called); in message_begin_cb,
.i dont known what happend.please give me some advice.thank you

**Comment by indutny** [comment]
It'd help if the code that you pasted would be compiled and run. Could you create a gist on gist.github.com with the full code that reproduces the issue?

**Comment by jiamuluo** [comment]
i am so sorry.the part of my http-parse code cannot compiled and run independently,but i would show my code here.

**Comment by jiamuluo** [comment]
> It'd help if the code that you pasted would be compiled and run. Could you create a gist on https://gist.github.com with the full code that reproduces the issue?

i am so sorry.the part of my http-parse code cannot compiled and run independently,but i would show my code here.

**Comment by jiamuluo** [comment]
> It'd help if the code that you pasted would be compiled and run. Could you create a gist on https://gist.github.com with the full code that reproduces the issue?

/*
 * @Author: jiamu 
 * @Date: 2018-10-29 10:36:27 
 * @Last Modified by: jiamu
 * @Last Modified time: 2018-10-29 20:59:32
 */
#include "snort_http.h"
#include "http_parser.h"
#include <assert.h>
#include "snort_file.h"
#include "list.h"
#include "record_data.h"
#include "protocol.h"
#include "cJSON.h"
#include "log.h"

enum ip_conntrack_dir {
	IP_CT_DIR_ORIGINAL,
	IP_CT_DIR_REPLY,
	IP_CT_DIR_MAX
};

#undef TRUE
#define TRUE 1
#undef FALSE
#define FALSE 0

#define HTTP_PORT 80

#define MAX_HEADERS 20
#define MAX_ELEMENT_SIZE 2048
#define MAX_CHUNKS 16

#define MIN(a,b) ((a) < (b) ? (a) : (b))

//#define ARRAY_SIZE(x) (sizeof(x) / sizeof(*x))
#define HTTP_OVER_TIME 7

struct message {
  const char *name; // for debugging purposes
  const char *raw;
  enum http_parser_type type;
  enum http_method method;
  int status_code;
  char response_status[MAX_ELEMENT_SIZE];
  char request_path[MAX_ELEMENT_SIZE];
  char request_url[MAX_ELEMENT_SIZE];
  char fragment[MAX_ELEMENT_SIZE];
  char query_string[MAX_ELEMENT_SIZE];
  char body[MAX_ELEMENT_SIZE];
  size_t body_size;
  const char *host;
  const char *userinfo;
  uint16_t port;
  int num_headers;
  enum { NONE=0, FIELD, VALUE } last_header_element;
  char headers [MAX_HEADERS][2][MAX_ELEMENT_SIZE];
  int should_keep_alive;

  int num_chunks;
  int num_chunks_complete;
  int chunk_lengths[MAX_CHUNKS];

  const char *upgrade; // upgraded body

  unsigned short http_major;
  unsigned short http_minor;

  int message_begin_cb_called;
  int headers_complete_cb_called;
  int message_complete_cb_called;
  int status_cb_called;
  int message_complete_on_eof;
  int body_is_final;
};

#define HTTP_FILTER_FILE "/etc/traffic-insight/http_filter.json"
typedef struct
{
	char strFilter[16];
	struct list_head list;
}HTTP_FILTER_INFO;

extern void record_http_cb(struct ev_loop *loop, ev_timer *watcher, int revents);
static struct list_head stFilterList;
static struct list_head stHttpList;
static struct list_head stFindList;
static http_parser *parser;
static int num_messages;
static struct message messages[2];
static int currently_parsing_eof;
static ev_timer http_watcher;

/* strnlen() is a POSIX.2008 addition. Can't rely on it being available so
 * define it ourselves.
 */
size_t
strnlen(const char *s, size_t maxlen)
{
	const char *p;

	p = memchr(s, '\0', maxlen);
	if (p == NULL)
		return maxlen;

	return p - s;
}

size_t strlncat(char *dst, size_t len, const char *src, size_t n)
{
	size_t slen;
	size_t dlen;
	size_t rlen;
	size_t ncpy;

	slen = strnlen(src, n);
	dlen = strnlen(dst, len);

	if (dlen < len) 
	{
		rlen = len - dlen;
		ncpy = slen < rlen ? slen : (rlen - 1);
		memcpy(dst + dlen, src, ncpy);
		dst[dlen + ncpy] = '\0';
	}

	assert(len > slen + dlen);
	return slen + dlen;
}

size_t
strlncpy(char *dst, size_t len, const char *src, size_t n)
{
	size_t slen;
	size_t ncpy;

	slen = strnlen(src, n);

	if (len > 0) 
	{
		ncpy = slen < len ? slen : (len - 1);
		memcpy(dst, src, ncpy);
		dst[ncpy] = '\0';
	}

	assert(len > slen);
	return slen;
}

int message_begin_cb (http_parser *p)
{
	assert(p == parser);
	assert(!messages[num_messages].message_begin_cb_called);
	messages[num_messages].message_begin_cb_called = TRUE;

	return 0;
}
int header_field_cb (http_parser *p, const char *buf, size_t len)
{
    
	assert(p == parser);
	struct message *m = &messages[num_messages];

	if (m->last_header_element != FIELD)
	m->num_headers++;
	if(m->num_headers > MAX_HEADERS)
	{
		return -1;
	}
	strlncat(m->headers[m->num_headers-1][0],
			sizeof(m->headers[m->num_headers-1][0]),
			buf,
			len);

	m->last_header_element = FIELD;
	//printf("%s :buf-->%s \n",__FUNCTION__,m->headers[m->num_headers-1][0]);

	return 0;
}

int header_value_cb (http_parser *p, const char *buf, size_t len)
{
	
	assert(p == parser);
	struct message *m = &messages[num_messages];

	strlncat(m->headers[m->num_headers-1][1],
			sizeof(m->headers[m->num_headers-1][1]),
			buf,
			len);

	m->last_header_element = VALUE;
	//printf("%s :buf-->%s \n",__FUNCTION__,m->headers[m->num_headers-1][1]);

	return 0;
}

int request_url_cb (http_parser *p, const char *buf, size_t len)
{
	
	assert(p == parser);
	strlncat(messages[num_messages].request_url,
			sizeof(messages[num_messages].request_url),
			buf,
			len);
	//printf("%s :buf-->%s \n",__FUNCTION__,messages[num_messages].request_url);
	return 0;
}

int response_status_cb (http_parser *p, const char *buf, size_t len)
{
	//printf("%s enter \n",__FUNCTION__);
	assert(p == parser);

	messages[num_messages].status_cb_called = TRUE;

	strlncat(messages[num_messages].response_status,
			sizeof(messages[num_messages].response_status),
			buf,
			len);
	//printf("%s :buf-->%s \n",__FUNCTION__,messages[num_messages].response_status);

  	return 0;
}

void check_body_is_final (const http_parser *p)
{

	if (messages[num_messages].body_is_final) 
	{
		fprintf(stderr, "\n\n *** Error http_body_is_final() should return 1 "
						"on last on_body callback call "
						"but it doesn't! ***\n\n");
		assert(0);
		abort();
	}
	messages[num_messages].body_is_final = http_body_is_final(p);
}

int body_cb (http_parser *p, const char *buf, size_t len)
{
	assert(p == parser);
	strlncat(messages[num_messages].body,
			sizeof(messages[num_messages].body),
			buf,
			len);
	messages[num_messages].body_size += len;
	check_body_is_final(p);
	//printf("%s :buf-->%s \n",__FUNCTION__,messages[num_messages].body); /*body不一定可见*/
	//printf("body_cb: '%s'\n", requests[num_messages].body);
	return 0;
}
/**
 * @brief 
 * 	头部处理完成
 * @param p 
 * @return int 
 */
int headers_complete_cb (http_parser *p)
{

	assert(p == parser);
	messages[num_messages].method = parser->method;
	messages[num_messages].status_code = parser->status_code;
	messages[num_messages].http_major = parser->http_major;
	messages[num_messages].http_minor = parser->http_minor;
	messages[num_messages].headers_complete_cb_called = TRUE;
	messages[num_messages].should_keep_alive = http_should_keep_alive(parser);
	
  	return 0;
}

int message_complete_cb (http_parser *p)
{
	assert(p == parser);
	if (messages[num_messages].should_keep_alive != http_should_keep_alive(parser))
	{
		fprintf(stderr, "\n\n *** Error http_should_keep_alive() should have same "
						"value in both on_message_complete and on_headers_complete "
						"but it doesn't! ***\n\n");
		assert(0);
		abort();
	}

	if (messages[num_messages].body_size &&
		http_body_is_final(p) &&
		!messages[num_messages].body_is_final)
	{
		fprintf(stderr, "\n\n *** Error http_body_is_final() should return 1 "
						"on last on_body callback call "
						"but it doesn't! ***\n\n");
		assert(0);
		abort();
	}

	messages[num_messages].message_complete_cb_called = TRUE;

	messages[num_messages].message_complete_on_eof = currently_parsing_eof;

	//num_messages++;
	
  return 0;
}

int chunk_header_cb (http_parser *p)
{
	
	assert(p == parser);
	int chunk_idx = messages[num_messages].num_chunks;
	messages[num_messages].num_chunks++;
	if (chunk_idx < MAX_CHUNKS) {
	messages[num_messages].chunk_lengths[chunk_idx] = p->content_length;
	}
	
  	return 0;
}
int chunk_complete_cb (http_parser *p)
{
	//printf("%s enter \n",__FUNCTION__);
  	assert(p == parser);

	/* Here we want to verify that each chunk_header_cb is matched by a
	* chunk_complete_cb, so not only should the total number of calls to
	* both callbacks be the same, but they also should be interleaved
	* properly */
	assert(messages[num_messages].num_chunks ==
			messages[num_messages].num_chunks_complete + 1);

	messages[num_messages].num_chunks_complete++;
	//printf("%s exit \n",__FUNCTION__);
	
  	return 0;
}

static http_parser_settings settings =
  {.on_message_begin = message_begin_cb
  ,.on_header_field = header_field_cb
  ,.on_header_value = header_value_cb
  ,.on_url = request_url_cb
  ,.on_status = response_status_cb
  ,.on_body = body_cb
  ,.on_headers_complete = headers_complete_cb
  ,.on_message_complete = message_complete_cb
  ,.on_chunk_header = chunk_header_cb
  ,.on_chunk_complete = chunk_complete_cb
  };

/**
 * @brief 
 *  
 * @param loop 
 * @return int 
 */
int http_insight_init(void *loop)
{
	unsigned long version;
	unsigned major;
	unsigned minor;
	unsigned patch;
	
    version = http_parser_version();
    major = (version >> 16) & 255;
    minor = (version >> 8) & 255;
    patch = version & 255;
    printf("http_parser v%u.%u.%u (0x%06lx)\n", major, minor, patch, version);

    parser = calloc(1,sizeof(http_parser));
    if(NULL == parser)
    {
        return RET_FAILED;
    }
    memset(parser,0,sizeof(http_parser));
	//parser.data = 
	init_list_head(&stHttpList);
	init_list_head(&stFindList);

	http_filter_init();

	http_watcher.data = &stHttpList;

    return RET_SUCCESS;
}

int do_handle_message(struct tuple4 *addr,struct ethhdr *pstEthInfo,int direction,void *Conn)
{
	
	return RET_FAILED;
}

int start_insight_http(void *pri)
{
	return RET_FAILED;
}

int do_insight_http(void *data,int slDataLen,int slProtocol,
	struct tuple4 *addr,struct ethhdr *pstEthInfo,int direction,NIDS_CONNTRACK_RECORD *pstConn)
//int do_insight_http(void *pri)
{

	
    if(//slProtocol != IPPROTO_TCP || 
       (direction == IP_CT_DIR_ORIGINAL && addr->dest != HTTP_PORT) ||
       (direction == IP_CT_DIR_REPLY    && addr->source != HTTP_PORT)
       )
    {
        return RET_FAILED;
    }

	if( IP_CT_DIR_REPLY == direction && 
		(CONN_MAIN_INVALID != pstConn->eMainType  ||
		!CHECK_STREAM_ACTION(pstConn->eSubType,_STREAM_GATHER_HTTP))
		)
	{
		return RET_SUCCESS;
	}
	
	num_messages = 0;
    bzero(messages,sizeof(messages));
	messages[num_messages].message_begin_cb_called = FALSE;
    http_parser_init(parser, HTTP_BOTH);

    size_t nparsed = http_parser_execute(parser, &settings, data, slDataLen);


	if(nparsed == slDataLen)
	{
		if(IP_CT_DIR_ORIGINAL == direction && messages[0].method != HTTP_GET)
			return RET_SUCCESS;
		if(IP_CT_DIR_REPLY == direction && (messages[0].status_code < 200 || messages[0].status_code > 299))
			return RET_SUCCESS;
		return do_handle_message(addr,pstEthInfo,direction,pstConn);
	}
    return RET_FAILED;
}


/**
 * @brief 
 *  here is a sample 
 * @param argc 
 * @param argv 
 * @return int 
 */
int main(int argc,char **argv)
{
    //http_insight_init();

    //getdata
    
    //do_insight_http();
}

**Comment by indutny** [comment]
@jiamuluo could you move this to https://gist.github.com/ ?

**Comment by indutny** [comment]
The formatting messes up the source code, it is still very hard to get a grok of it.

**Comment by jiamuluo** [comment]
> @jiamuluo could you move this to https://gist.github.com/ ?

https://gist.github.com/jiamuluo/f8bbfd12a5b8da92459123cdc55defd3.
do you mean this?this is a sample code that indicates my code how to run.But it cannot compile. i guess that message_begin_cb is called twice in one http steam.i am verifying that.

**Comment by indutny** [comment]
Superficially, it looks like `//num_messages++;` might be the culprit.

**Comment by jiamuluo** [comment]
> num_messages

i don’t think so.i will zero num_messages when i call do_insight_http.

**Comment by indutny** [comment]
Well, you don't increment it so it should always stay zero regardless of what happens in `do_insight_http`.

**Comment by jiamuluo** [comment]
> Well, you don't increment it so it should always stay zero regardless of what happens in `do_insight_http`.

but as you see,just zero num_messages and messages in do_insight_http. i have tried to define messages[2]，but it looks like uesless. i will get this problem,though it is just very few times.

**Comment by indutny** [comment]
One TCP connection could be used for sending many HTTP requests. Are you sure that you are receiving just on request and not multiple?

**Comment by jiamuluo** [comment]
> One TCP connection could be used for sending many HTTP requests. Are you sure that you are receiving just on request and not multiple?
maybe i get your point.what you mean is i should defines messages as an array,so i can get mutiple request.that is right?

**Comment by indutny** [comment]
I'd say - yes!

**Comment by jiamuluo** [comment]
thanks a lot

**Comment by indutny** [comment]
You're welcome!
