### ISSUE TITLE
What about parsing http messages by hardware?

### ISSUE THREAD

**Issue by iamybj** [nodejs/http-parser#450]
What about parsing http messages by hardware?

**Comment by indutny** [comment]
Are you suggesting that we should develop hardware?

**Comment by iamybj** [comment]
Why not ?
In old times, CPU even cannot do float point operating, some advanced computer use coprocessor do that.
And now, GPU is also a coprocessor to help CPU do video computing task.
I think it may be product a coprocessor that help CPU to do http, json, xml, MD5, RSA, etc tasks.

**Comment by indutny** [comment]
I'm sorry, but maintainers of this project have no plans for developing such hardware in near future. Thank you for the suggestion, though!
