### ISSUE TITLE
Content-Length with obsolete line folding is accepted with invalid input

### ISSUE THREAD

**Issue by obatysh** [nodejs/http-parser#456]
According to https://tools.ietf.org/html/rfc7230#section-3.2.4
requests/responses with obsolete line folding can be rejected or obs-fold can be treated as one or more spaces.
obs-fold       = CRLF 1*( SP / HTAB )

Currently any input after an obsolete line folding in Content-Length field would be accepted.
Example request:
"POST / HTTP/1.1\r\n"
"Content-Length:  42\r\n"
" ANY TEXT\r\n"  // would be accepted and reported as part of Content-Length header field value
"\r\n"
...

**Comment by obatysh** [comment]
There is no test yet, and it was reporting error before the commit https://github.com/nodejs/http-parser/commit/01da95feade5e5612499f5374498e7968c1a4a82 was introduced.

The issue happens because after obsolete line folding is discovered the parser goes back to s_header_value_start. But as new content length states h_content_length_num, h_content_length_ws are not handled there it goes to default case and h_general state.

**Comment by indutny** [comment]
Thank you for checking it. Your analysis of the code path is absolutely correct! Did I understand it right, that after 01da95f the bug is no longer reproducible?

**Comment by obatysh** [comment]
No, vice versa, the bug appears after 
https://github.com/nodejs/http-parser/commit/01da95feade5e5612499f5374498e7968c1a4a82

**Comment by indutny** [comment]
@obatysh would you care to clarify if this error is actually reproducible and you experienced it?

**Comment by indutny** [comment]
Nevermind, I can reproduce it now.
