### ISSUE TITLE
Bad pointer arithmetic in header field parsing

### ISSUE THREAD

**Issue by bnoordhuis** [nodejs/http-parser#473]
https://github.com/nodejs/http-parser/blob/c5c45636b85e7598223adede6ba2d8cb8fe03ebe/http_parser.c#L1259-L1266

What that code calls `limit` is actually the number of remaining characters.

`p+1 < data+limit` must be wrong because `data+limit` is not fixed, it gets smaller as the `p` on line 1260 gets bigger.

Say, `len == 8` and `p == data + 5`, then `data + len - p == 3`. Ergo, `p+1 < data+limit` is always false in that case.

**Comment by indutny** [comment]
Let's do some math:

```
len = 16000
p - data = 100
max_header_size = 8000
limit = 7900
```

It seems that there would be some `p` for which the condition is going to be false?

**Comment by bnoordhuis** [comment]
IIUC your example, `limit` gets clamped to 8000 because `MIN(16000 - 100, 8000)`.
