### ISSUE TITLE
Error handling: how to get specific error messages?

### ISSUE THREAD

**Issue by wonter** [nodejs/http-parser#476]
I found the basic error handling in `README`:

```c
if (parser->upgrade) {
  /* handle new protocol */
} else if (nparsed != recved) {
  /* Handle error. Usually just close the connection. */
}
```

But how can I get more specific error messages?

Something like  `invalid HTTP method` error message.

**Comment by ploxiln** [comment]
try:

```c
const char *err_name = http_errno_name(HTTP_PARSER_ERRNO(parser));
const char *err_desc = http_errno_description(HTTP_PARSER_ERRNO(parser));
```

**Comment by wonter** [comment]
> try:
> 
> ```c
> const char *err_name = http_errno_name(HTTP_PARSER_ERRNO(parser));
> const char *err_desc = http_errno_description(HTTP_PARSER_ERRNO(parser));
> ```

Sorry, I have another question.

Is HTTP_PARSER_ERRNO(parser) always be set when an error occurred?? 

I mean, will HTTP_PARSER_ERRNO(parser) be set when `nparsed != recved`?

**Comment by ploxiln** [comment]
yes

**Comment by ploxiln** [comment]
to be sure you can check `if (HTTP_PARSER_ERRNO(parser) != HPE_OK)`

**Comment by wonter** [comment]
> to be sure you can check `if (HTTP_PARSER_ERRNO(parser) != 0)`

thx!
