### ISSUE TITLE
Is here a bug in on_body call?

### ISSUE THREAD

**Issue by ssrlive** [nodejs/http-parser#482]
When I test the bench code, I find some issue. Is it a bug?

When the `on_body` called, the input pointer `at` pointed to `hello world`, `NOT` to `b`. 

Why?
```
static int on_body(http_parser* p, const char *at, size_t length) {
  return 0;
}
```

https://github.com/nodejs/http-parser/blob/master/bench.c#L45

![image](https://user-images.githubusercontent.com/30760636/59083005-2a20ca80-8928-11e9-8f66-d93172a1a866.png)

And if it's `NOT` a bug, why?

**Comment by indutny** [comment]
There is a separate callback for `chunk_header`, if you need it. Usually, though, it would unwise to have a different API for chunked-encoding and fixed bodies.

TL;DR: This is desired behavior and not a bug.

Thanks for filing an issue, though!
