### ISSUE TITLE
Parsing trailers

### ISSUE THREAD

**Issue by Chuongv** [nodejs/http-parser#495]
I noticed that when the http-parser parses trailers, it does not call the [on_headers_complete](https://github.com/nodejs/http-parser/blob/master/http_parser.h#L330) after the trailers have been parsed. It instead goes to `on_message_complete`

Is that the intended behavior? Was not sure if my implementation is wrong or if this is expected.

**Comment by bnoordhuis** [comment]
Yes, that's the expected behavior. `on_headers_complete` signals the transition from headers to body, `on_message_complete` from body or trailing headers to end-of-message.

**Comment by Chuongv** [comment]
Sweet thanks, that aligns to what I am seeing.
