### ISSUE TITLE
how does the http-parser to support the multi threads

### ISSUE THREAD

**Issue by darmenliu** [nodejs/http-parser#498]
hi, I have a sence that client send the big data request, then server will use multi thread to process the request, these threads might invoke parser parallel, I'm not sure hao do I support the multi threads via http-parser.

**Comment by bnoordhuis** [comment]
http-parser is oblivious to threads. As long as there's only one thread at a time operating on the `struct http_parser` instance and provided you issue the proper memory barrier when passing the struct between threads, everything is fine.
