### ISSUE TITLE
Rename primary branch to main

### ISSUE THREAD

**Issue by mhdawson** [nodejs/http-parser#532]
We are going through all of the node.js repositories to rename the primary branch to main. Please see nodejs/node#33864 for more context.

I saw the note on the readme about the repo not being actively maintained, I also don't see any githbub workflows so I don't think there should be issues with the rename.

Please let me know if there are any concerns otherwise I'll look to do the rename Friday May 4th.

**Comment by indutny** [comment]
I don't imagine there'd be any problems. Feel free to do it whenever.

**Comment by mhdawson** [comment]
@indutny thanks, done.
