### ISSUE TITLE
error parsing response

### ISSUE THREAD

**Issue by arhrodriguez** [nodejs/http-parser#8]
We encountered a bug while parsing the above Url : http://www.ufc.com

The problem appears to be the actual server response witch is the following :

HTTP/1.1 200 OK
Server: Microsoft-IIS/6.0
X-Powered-By: ASP.NET
en-US Content-Type: text/xml  // this is the problem
Content-Type: text/xml
Content-Length: 18293
Date: Fri, 23 Jul 2010 18:45:38 GMT
Connection: keep-alive

<?xml version="1.0" encoding="utf-8" standalone="yes" ?>
<news>
.<parameters>
..<rotatetime>10</rotatetime>
.<repeatmode>loop</repeatmode>
.</parameters>
.<ads>
..

The parser does not expect an blank space on  state "s_header_field".  We got it working just by adding an condition to ignore this space.

if(ch=='  ' ){break;}

We dont dont know if this fix, is actually causing others problems (at least not as far as we know).

I guess the web browser parser ignores this space because its work. Try it.

**Comment by arashifunsho** [comment]
Is there any example that can help parse http response string gotten from socket connection on ARM embedded devices.

I need the Response code and Message Body (which is a JSON string that I can parse)
